/*
 * Generated by Bluespec Compiler, version 2024.07 (build b4f31dbe)
 * 
 * On Mon Oct 21 14:14:37 IST 2024
 * 
 */
#include "bluesim_primitives.h"
#include "model_mk_Test.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mk_Test::MODEL_mk_Test()
{
  mk_Test_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mk_Test()
{
  MODEL_mk_Test *model = new MODEL_mk_Test();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mk_Test &INST_top = *((MOD_mk_Test *)(instance_ptr));
	 INST_top.DEF_b__h17397 = INST_top.INST_count.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_inp = (INST_top.DEF_b__h17397) == 1u;
	 INST_top.DEF_WILL_FIRE_RL_inp = INST_top.DEF_CAN_FIRE_RL_inp;
	 INST_top.DEF_CAN_FIRE_RL_obj_mac_res1 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_obj_mac_res1 = INST_top.DEF_CAN_FIRE_RL_obj_mac_res1;
	 INST_top.DEF_CAN_FIRE_RL_obj_mac_stage1 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_obj_mac_stage1 = INST_top.DEF_CAN_FIRE_RL_obj_mac_stage1;
	 INST_top.DEF_CAN_FIRE_RL_obj_mac_stage2 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_obj_mac_stage2 = INST_top.DEF_CAN_FIRE_RL_obj_mac_stage2;
	 INST_top.DEF_CAN_FIRE_RL_obj_mac_stage3 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_obj_mac_stage3 = INST_top.DEF_CAN_FIRE_RL_obj_mac_stage3;
	 INST_top.DEF_CAN_FIRE_RL_obj_mac_stage4 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_obj_mac_stage4 = INST_top.DEF_CAN_FIRE_RL_obj_mac_stage4;
	 INST_top.DEF_CAN_FIRE_RL_res = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_res = INST_top.DEF_CAN_FIRE_RL_res;
	 INST_top.DEF_CAN_FIRE_RL_stall = primSLT8(1u,
						   32u,
						   (tUInt32)(INST_top.DEF_b__h17397),
						   32u,
						   11u) && !primSLE8(1u,
								     32u,
								     (tUInt32)(INST_top.DEF_b__h17397),
								     32u,
								     1u);
	 INST_top.DEF_WILL_FIRE_RL_stall = INST_top.DEF_CAN_FIRE_RL_stall;
	 INST_top.DEF_CAN_FIRE_RL_stop = (INST_top.DEF_b__h17397) == 11u;
	 INST_top.DEF_WILL_FIRE_RL_stop = INST_top.DEF_CAN_FIRE_RL_stop;
	 if (INST_top.DEF_WILL_FIRE_RL_res)
	   INST_top.RL_res();
	 if (INST_top.DEF_WILL_FIRE_RL_obj_mac_res1)
	   INST_top.RL_obj_mac_res1();
	 if (INST_top.DEF_WILL_FIRE_RL_obj_mac_stage4)
	   INST_top.RL_obj_mac_stage4();
	 if (INST_top.DEF_WILL_FIRE_RL_obj_mac_stage3)
	   INST_top.RL_obj_mac_stage3();
	 if (INST_top.DEF_WILL_FIRE_RL_obj_mac_stage2)
	   INST_top.RL_obj_mac_stage2();
	 if (INST_top.DEF_WILL_FIRE_RL_obj_mac_stage1)
	   INST_top.RL_obj_mac_stage1();
	 if (INST_top.DEF_WILL_FIRE_RL_inp)
	   INST_top.RL_inp();
	 if (INST_top.DEF_WILL_FIRE_RL_stall)
	   INST_top.RL_stall();
	 if (INST_top.DEF_WILL_FIRE_RL_stop)
	   INST_top.RL_stop();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_rg_a.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_rg_b.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_rg_c.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_x.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_y.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_z.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp00.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp01.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp07.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp16.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp21.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp30.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp35.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp41.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp50.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp57.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp77.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s16.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp00_s2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp10_s2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp01_s2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp35_s2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp57_s2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp77_s2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s21.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s22.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s23.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s15_s2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s11_s2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s16_s2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s31.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s32.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s33.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s34.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s35.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s36.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp00_s3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp01_s3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp10_s3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp77_s3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s11_s3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s16_s3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s21_s3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s22_s3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s23_s3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s41.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s42.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s43.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_s44.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_obj_mac_pp00_s4.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mk_Test::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mk_Test_instance = new MOD_mk_Test(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mk_Test_instance->set_clk_0)("CLK");
}
void MODEL_mk_Test::destroy_model()
{
  delete mk_Test_instance;
  mk_Test_instance = NULL;
}
void MODEL_mk_Test::reset_model(bool asserted)
{
  (mk_Test_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mk_Test::get_instance()
{
  return mk_Test_instance;
}

/* Fill in version numbers */
void MODEL_mk_Test::get_version(char const **name, char const **build)
{
  *name = "2024.07";
  *build = "b4f31dbe";
}

/* Get the model creation time */
time_t MODEL_mk_Test::get_creation_time()
{
  
  /* Mon Oct 21 08:44:37 UTC 2024 */
  return 1729500277llu;
}

/* State dumping function */
void MODEL_mk_Test::dump_state()
{
  (mk_Test_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mk_Test & mk_Test_backing(tSimStateHdl simHdl)
{
  static MOD_mk_Test *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mk_Test(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mk_Test::dump_VCD_defs()
{
  (mk_Test_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mk_Test::dump_VCD(tVCDDumpType dt)
{
  (mk_Test_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mk_Test_backing(sim_hdl));
}
