/*
 * Generated by Bluespec Compiler, version 2024.07 (build b4f31dbe)
 * 
 * On Sat Oct 12 18:08:16 IST 2024
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkMAC_h__
#define __mkMAC_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkMAC module */
class MOD_mkMAC : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_a_r;
  MOD_Reg<tUInt32> INST_b_r;
  MOD_Reg<tUInt32> INST_c_r;
  MOD_Reg<tUInt32> INST_out_r;
  MOD_Reg<tUInt8> INST_s1_r;
 
 /* Constructor */
 public:
  MOD_mkMAC(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_get_input;
  tUInt32 PORT_get_input_a;
  tUInt32 PORT_get_input_b;
  tUInt32 PORT_get_input_c;
  tUInt8 PORT_get_input_s1_or_s0;
  tUInt8 PORT_RDY_get_input;
  tUInt32 PORT_get_result;
  tUInt8 PORT_RDY_get_result;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_get_input;
  tUInt8 DEF_WILL_FIRE_RL_compute;
  tUInt8 DEF_CAN_FIRE_RL_compute;
  tUInt8 DEF_CAN_FIRE_get_result;
  tUInt8 DEF_CAN_FIRE_get_input;
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
  void RL_compute();
 
 /* Methods */
 public:
  void METH_get_input(tUInt32 ARG_get_input_a,
		      tUInt32 ARG_get_input_b,
		      tUInt32 ARG_get_input_c,
		      tUInt8 ARG_get_input_s1_or_s0);
  tUInt8 METH_RDY_get_input();
  tUInt32 METH_get_result();
  tUInt8 METH_RDY_get_result();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkMAC &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkMAC &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkMAC &backing);
};

#endif /* ifndef __mkMAC_h__ */
