/*
 * Generated by Bluespec Compiler, version 2024.07 (build b4f31dbe)
 * 
 * On Sat Oct 12 18:08:16 IST 2024
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTb_h__
#define __mkTb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkMAC.h"


/* Class declaration for the mkTb module */
class MOD_mkTb : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_count;
  MOD_mkMAC INST_mac;
  MOD_Reg<tUInt32> INST_rg_a;
  MOD_Reg<tUInt32> INST_rg_b;
  MOD_Reg<tUInt32> INST_rg_c;
  MOD_Reg<tUInt8> INST_rg_s1_or_s2;
 
 /* Constructor */
 public:
  MOD_mkTb(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_res;
  tUInt8 DEF_CAN_FIRE_RL_res;
  tUInt8 DEF_WILL_FIRE_RL_stall;
  tUInt8 DEF_CAN_FIRE_RL_stall;
  tUInt8 DEF_WILL_FIRE_RL_inp;
  tUInt8 DEF_CAN_FIRE_RL_inp;
  tUInt32 DEF_b__h269;
 
 /* Local definitions */
 private:
  tUInt32 DEF_count_PLUS_1___d7;
 
 /* Rules */
 public:
  void RL_inp();
  void RL_stall();
  void RL_res();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTb &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTb &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTb &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTb &backing);
};

#endif /* ifndef __mkTb_h__ */
