SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/arr_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mk_sys_arr.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mk_sys_arr
MODULE   = test_systolic_array

include $(shell cocotb-config --makefiles)/Makefile.sim
