SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/MAC_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mk_mac.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mk_mac
MODULE   = test_mac

include $(shell cocotb-config --makefiles)/Makefile.sim
