/*
 * Generated by Bluespec Compiler, version 2024.07 (build b4f31dbe)
 * 
 * On Mon Oct 21 14:14:37 IST 2024
 * 
 */
#include "bluesim_primitives.h"
#include "mk_Test.h"


/* String declarations */
static std::string const __str_literal_1("%d  INT8 MAC O/P: %d", 20u);


/* Constructor */
MOD_mk_Test::MOD_mk_Test(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_count(simHdl, "count", this, 32u, 1u, (tUInt8)0u),
    INST_obj_mac_pp00(simHdl, "obj_mac_pp00", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp00_s2(simHdl, "obj_mac_pp00_s2", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp00_s3(simHdl, "obj_mac_pp00_s3", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp00_s4(simHdl, "obj_mac_pp00_s4", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp01(simHdl, "obj_mac_pp01", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp01_s2(simHdl, "obj_mac_pp01_s2", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp01_s3(simHdl, "obj_mac_pp01_s3", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp07(simHdl, "obj_mac_pp07", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp10(simHdl, "obj_mac_pp10", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp10_s2(simHdl, "obj_mac_pp10_s2", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp10_s3(simHdl, "obj_mac_pp10_s3", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp16(simHdl, "obj_mac_pp16", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp21(simHdl, "obj_mac_pp21", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp30(simHdl, "obj_mac_pp30", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp35(simHdl, "obj_mac_pp35", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp35_s2(simHdl, "obj_mac_pp35_s2", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp41(simHdl, "obj_mac_pp41", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp50(simHdl, "obj_mac_pp50", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp57(simHdl, "obj_mac_pp57", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp57_s2(simHdl, "obj_mac_pp57_s2", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp77(simHdl, "obj_mac_pp77", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp77_s2(simHdl, "obj_mac_pp77_s2", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_pp77_s3(simHdl, "obj_mac_pp77_s3", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s11(simHdl, "obj_mac_s11", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s11_s2(simHdl, "obj_mac_s11_s2", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s11_s3(simHdl, "obj_mac_s11_s3", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s12(simHdl, "obj_mac_s12", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s13(simHdl, "obj_mac_s13", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s14(simHdl, "obj_mac_s14", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s15(simHdl, "obj_mac_s15", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s15_s2(simHdl, "obj_mac_s15_s2", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s16(simHdl, "obj_mac_s16", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s16_s2(simHdl, "obj_mac_s16_s2", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s16_s3(simHdl, "obj_mac_s16_s3", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s21(simHdl, "obj_mac_s21", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s21_s3(simHdl, "obj_mac_s21_s3", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s22(simHdl, "obj_mac_s22", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s22_s3(simHdl, "obj_mac_s22_s3", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s23(simHdl, "obj_mac_s23", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s23_s3(simHdl, "obj_mac_s23_s3", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s31(simHdl, "obj_mac_s31", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s32(simHdl, "obj_mac_s32", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s33(simHdl, "obj_mac_s33", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s34(simHdl, "obj_mac_s34", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s35(simHdl, "obj_mac_s35", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s36(simHdl, "obj_mac_s36", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s41(simHdl, "obj_mac_s41", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s42(simHdl, "obj_mac_s42", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s43(simHdl, "obj_mac_s43", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_s44(simHdl, "obj_mac_s44", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_obj_mac_x(simHdl, "obj_mac_x", this, 8u, (tUInt8)170u, (tUInt8)0u),
    INST_obj_mac_y(simHdl, "obj_mac_y", this, 8u, (tUInt8)170u, (tUInt8)0u),
    INST_obj_mac_z(simHdl, "obj_mac_z", this, 16u, 43690u, (tUInt8)0u),
    INST_rg_a(simHdl, "rg_a", this, 8u, (tUInt8)100u, (tUInt8)0u),
    INST_rg_b(simHdl, "rg_b", this, 8u, (tUInt8)156u, (tUInt8)0u),
    INST_rg_c(simHdl, "rg_c", this, 32u, 500u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 85u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mk_Test::init_symbols_0()
{
  init_symbol(&symbols[0u], "b__h17397", SYM_DEF, &DEF_b__h17397, 32u);
  init_symbol(&symbols[1u], "CAN_FIRE_RL_inp", SYM_DEF, &DEF_CAN_FIRE_RL_inp, 1u);
  init_symbol(&symbols[2u], "CAN_FIRE_RL_obj_mac_res1", SYM_DEF, &DEF_CAN_FIRE_RL_obj_mac_res1, 1u);
  init_symbol(&symbols[3u],
	      "CAN_FIRE_RL_obj_mac_stage1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_obj_mac_stage1,
	      1u);
  init_symbol(&symbols[4u],
	      "CAN_FIRE_RL_obj_mac_stage2",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_obj_mac_stage2,
	      1u);
  init_symbol(&symbols[5u],
	      "CAN_FIRE_RL_obj_mac_stage3",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_obj_mac_stage3,
	      1u);
  init_symbol(&symbols[6u],
	      "CAN_FIRE_RL_obj_mac_stage4",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_obj_mac_stage4,
	      1u);
  init_symbol(&symbols[7u], "CAN_FIRE_RL_res", SYM_DEF, &DEF_CAN_FIRE_RL_res, 1u);
  init_symbol(&symbols[8u], "CAN_FIRE_RL_stall", SYM_DEF, &DEF_CAN_FIRE_RL_stall, 1u);
  init_symbol(&symbols[9u], "CAN_FIRE_RL_stop", SYM_DEF, &DEF_CAN_FIRE_RL_stop, 1u);
  init_symbol(&symbols[10u], "count", SYM_MODULE, &INST_count);
  init_symbol(&symbols[11u], "obj_mac_pp00", SYM_MODULE, &INST_obj_mac_pp00);
  init_symbol(&symbols[12u], "obj_mac_pp00_s2", SYM_MODULE, &INST_obj_mac_pp00_s2);
  init_symbol(&symbols[13u], "obj_mac_pp00_s3", SYM_MODULE, &INST_obj_mac_pp00_s3);
  init_symbol(&symbols[14u], "obj_mac_pp00_s4", SYM_MODULE, &INST_obj_mac_pp00_s4);
  init_symbol(&symbols[15u], "obj_mac_pp01", SYM_MODULE, &INST_obj_mac_pp01);
  init_symbol(&symbols[16u], "obj_mac_pp01_s2", SYM_MODULE, &INST_obj_mac_pp01_s2);
  init_symbol(&symbols[17u], "obj_mac_pp01_s3", SYM_MODULE, &INST_obj_mac_pp01_s3);
  init_symbol(&symbols[18u], "obj_mac_pp07", SYM_MODULE, &INST_obj_mac_pp07);
  init_symbol(&symbols[19u], "obj_mac_pp10", SYM_MODULE, &INST_obj_mac_pp10);
  init_symbol(&symbols[20u], "obj_mac_pp10_s2", SYM_MODULE, &INST_obj_mac_pp10_s2);
  init_symbol(&symbols[21u], "obj_mac_pp10_s3", SYM_MODULE, &INST_obj_mac_pp10_s3);
  init_symbol(&symbols[22u], "obj_mac_pp16", SYM_MODULE, &INST_obj_mac_pp16);
  init_symbol(&symbols[23u], "obj_mac_pp21", SYM_MODULE, &INST_obj_mac_pp21);
  init_symbol(&symbols[24u], "obj_mac_pp30", SYM_MODULE, &INST_obj_mac_pp30);
  init_symbol(&symbols[25u], "obj_mac_pp35", SYM_MODULE, &INST_obj_mac_pp35);
  init_symbol(&symbols[26u], "obj_mac_pp35_s2", SYM_MODULE, &INST_obj_mac_pp35_s2);
  init_symbol(&symbols[27u], "obj_mac_pp41", SYM_MODULE, &INST_obj_mac_pp41);
  init_symbol(&symbols[28u], "obj_mac_pp50", SYM_MODULE, &INST_obj_mac_pp50);
  init_symbol(&symbols[29u], "obj_mac_pp57", SYM_MODULE, &INST_obj_mac_pp57);
  init_symbol(&symbols[30u], "obj_mac_pp57_s2", SYM_MODULE, &INST_obj_mac_pp57_s2);
  init_symbol(&symbols[31u], "obj_mac_pp77", SYM_MODULE, &INST_obj_mac_pp77);
  init_symbol(&symbols[32u], "obj_mac_pp77_s2", SYM_MODULE, &INST_obj_mac_pp77_s2);
  init_symbol(&symbols[33u], "obj_mac_pp77_s3", SYM_MODULE, &INST_obj_mac_pp77_s3);
  init_symbol(&symbols[34u], "obj_mac_s11", SYM_MODULE, &INST_obj_mac_s11);
  init_symbol(&symbols[35u], "obj_mac_s11_s2", SYM_MODULE, &INST_obj_mac_s11_s2);
  init_symbol(&symbols[36u], "obj_mac_s11_s3", SYM_MODULE, &INST_obj_mac_s11_s3);
  init_symbol(&symbols[37u], "obj_mac_s12", SYM_MODULE, &INST_obj_mac_s12);
  init_symbol(&symbols[38u], "obj_mac_s13", SYM_MODULE, &INST_obj_mac_s13);
  init_symbol(&symbols[39u], "obj_mac_s14", SYM_MODULE, &INST_obj_mac_s14);
  init_symbol(&symbols[40u], "obj_mac_s15", SYM_MODULE, &INST_obj_mac_s15);
  init_symbol(&symbols[41u], "obj_mac_s15_s2", SYM_MODULE, &INST_obj_mac_s15_s2);
  init_symbol(&symbols[42u], "obj_mac_s16", SYM_MODULE, &INST_obj_mac_s16);
  init_symbol(&symbols[43u], "obj_mac_s16_s2", SYM_MODULE, &INST_obj_mac_s16_s2);
  init_symbol(&symbols[44u], "obj_mac_s16_s3", SYM_MODULE, &INST_obj_mac_s16_s3);
  init_symbol(&symbols[45u], "obj_mac_s21", SYM_MODULE, &INST_obj_mac_s21);
  init_symbol(&symbols[46u], "obj_mac_s21_s3", SYM_MODULE, &INST_obj_mac_s21_s3);
  init_symbol(&symbols[47u], "obj_mac_s22", SYM_MODULE, &INST_obj_mac_s22);
  init_symbol(&symbols[48u], "obj_mac_s22_s3", SYM_MODULE, &INST_obj_mac_s22_s3);
  init_symbol(&symbols[49u], "obj_mac_s23", SYM_MODULE, &INST_obj_mac_s23);
  init_symbol(&symbols[50u], "obj_mac_s23_s3", SYM_MODULE, &INST_obj_mac_s23_s3);
  init_symbol(&symbols[51u], "obj_mac_s31", SYM_MODULE, &INST_obj_mac_s31);
  init_symbol(&symbols[52u], "obj_mac_s32", SYM_MODULE, &INST_obj_mac_s32);
  init_symbol(&symbols[53u], "obj_mac_s33", SYM_MODULE, &INST_obj_mac_s33);
  init_symbol(&symbols[54u], "obj_mac_s34", SYM_MODULE, &INST_obj_mac_s34);
  init_symbol(&symbols[55u], "obj_mac_s35", SYM_MODULE, &INST_obj_mac_s35);
  init_symbol(&symbols[56u], "obj_mac_s36", SYM_MODULE, &INST_obj_mac_s36);
  init_symbol(&symbols[57u], "obj_mac_s41", SYM_MODULE, &INST_obj_mac_s41);
  init_symbol(&symbols[58u], "obj_mac_s42", SYM_MODULE, &INST_obj_mac_s42);
  init_symbol(&symbols[59u], "obj_mac_s43", SYM_MODULE, &INST_obj_mac_s43);
  init_symbol(&symbols[60u], "obj_mac_s44", SYM_MODULE, &INST_obj_mac_s44);
  init_symbol(&symbols[61u], "obj_mac_x", SYM_MODULE, &INST_obj_mac_x);
  init_symbol(&symbols[62u], "obj_mac_y", SYM_MODULE, &INST_obj_mac_y);
  init_symbol(&symbols[63u], "obj_mac_z", SYM_MODULE, &INST_obj_mac_z);
  init_symbol(&symbols[64u], "RL_inp", SYM_RULE);
  init_symbol(&symbols[65u], "RL_obj_mac_res1", SYM_RULE);
  init_symbol(&symbols[66u], "RL_obj_mac_stage1", SYM_RULE);
  init_symbol(&symbols[67u], "RL_obj_mac_stage2", SYM_RULE);
  init_symbol(&symbols[68u], "RL_obj_mac_stage3", SYM_RULE);
  init_symbol(&symbols[69u], "RL_obj_mac_stage4", SYM_RULE);
  init_symbol(&symbols[70u], "RL_res", SYM_RULE);
  init_symbol(&symbols[71u], "RL_stall", SYM_RULE);
  init_symbol(&symbols[72u], "RL_stop", SYM_RULE);
  init_symbol(&symbols[73u], "rg_a", SYM_MODULE, &INST_rg_a);
  init_symbol(&symbols[74u], "rg_b", SYM_MODULE, &INST_rg_b);
  init_symbol(&symbols[75u], "rg_c", SYM_MODULE, &INST_rg_c);
  init_symbol(&symbols[76u], "WILL_FIRE_RL_inp", SYM_DEF, &DEF_WILL_FIRE_RL_inp, 1u);
  init_symbol(&symbols[77u],
	      "WILL_FIRE_RL_obj_mac_res1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_obj_mac_res1,
	      1u);
  init_symbol(&symbols[78u],
	      "WILL_FIRE_RL_obj_mac_stage1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_obj_mac_stage1,
	      1u);
  init_symbol(&symbols[79u],
	      "WILL_FIRE_RL_obj_mac_stage2",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_obj_mac_stage2,
	      1u);
  init_symbol(&symbols[80u],
	      "WILL_FIRE_RL_obj_mac_stage3",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_obj_mac_stage3,
	      1u);
  init_symbol(&symbols[81u],
	      "WILL_FIRE_RL_obj_mac_stage4",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_obj_mac_stage4,
	      1u);
  init_symbol(&symbols[82u], "WILL_FIRE_RL_res", SYM_DEF, &DEF_WILL_FIRE_RL_res, 1u);
  init_symbol(&symbols[83u], "WILL_FIRE_RL_stall", SYM_DEF, &DEF_WILL_FIRE_RL_stall, 1u);
  init_symbol(&symbols[84u], "WILL_FIRE_RL_stop", SYM_DEF, &DEF_WILL_FIRE_RL_stop, 1u);
}


/* Rule actions */

void MOD_mk_Test::RL_obj_mac_stage1()
{
  tUInt8 DEF_x__h3238;
  tUInt8 DEF_x__h2000;
  tUInt8 DEF_x__h4353;
  tUInt8 DEF_x__h5468;
  tUInt8 DEF_sum__h6504;
  tUInt8 DEF_x__h6474;
  tUInt8 DEF_x__h7456;
  tUInt8 DEF_x__h2387;
  tUInt8 DEF_x__h2454;
  tUInt8 DEF_x__h2544;
  tUInt8 DEF_x__h2909;
  tUInt8 DEF_x__h2976;
  tUInt8 DEF_x__h3124;
  tUInt8 DEF_x__h3501;
  tUInt8 DEF_x__h3568;
  tUInt8 DEF_x__h3658;
  tUInt8 DEF_x__h4022;
  tUInt8 DEF_x__h4089;
  tUInt8 DEF_x__h4237;
  tUInt8 DEF_x__h4616;
  tUInt8 DEF_x__h4683;
  tUInt8 DEF_x__h4773;
  tUInt8 DEF_x__h5137;
  tUInt8 DEF_x__h5204;
  tUInt8 DEF_x__h5352;
  tUInt8 DEF_x__h5773;
  tUInt8 DEF_x__h5837;
  tUInt8 DEF_y__h5838;
  tUInt8 DEF_x__h6156;
  tUInt8 DEF_x__h8912;
  tUInt8 DEF_x__h6754;
  tUInt8 DEF_x__h6818;
  tUInt8 DEF_x__h7136;
  tUInt8 DEF_x__h7614;
  tUInt8 DEF_x__h7681;
  tUInt8 DEF_x__h7771;
  tUInt8 DEF_x__h8029;
  tUInt8 DEF_x__h8096;
  tUInt8 DEF_x__h8244;
  tUInt8 DEF_y__h2842;
  tUInt8 DEF_y__h2050;
  tUInt8 DEF_y__h2048;
  tUInt8 DEF_x__h2047;
  tUInt8 DEF_y__h3057;
  tUInt8 DEF_y__h2046;
  tUInt8 DEF_x__h2045;
  tUInt8 DEF_y__h3180;
  tUInt8 DEF_y__h2044;
  tUInt8 DEF_x__h2043;
  tUInt8 DEF_cout__h2029;
  tUInt8 DEF_y__h2840;
  tUInt8 DEF_x__h2839;
  tUInt8 DEF_y__h2838;
  tUInt8 DEF_x__h2837;
  tUInt8 DEF_y__h3055;
  tUInt8 DEF_x__h3054;
  tUInt8 DEF_y__h3288;
  tUInt8 DEF_y__h3955;
  tUInt8 DEF_y__h3286;
  tUInt8 DEF_x__h3285;
  tUInt8 DEF_y__h4170;
  tUInt8 DEF_y__h3284;
  tUInt8 DEF_x__h3283;
  tUInt8 DEF_y__h4293;
  tUInt8 DEF_y__h3282;
  tUInt8 DEF_x__h3281;
  tUInt8 DEF_cout__h3267;
  tUInt8 DEF_y__h3953;
  tUInt8 DEF_x__h3952;
  tUInt8 DEF_y__h3951;
  tUInt8 DEF_x__h3950;
  tUInt8 DEF_y__h4168;
  tUInt8 DEF_x__h4167;
  tUInt8 DEF_y__h4403;
  tUInt8 DEF_y__h5070;
  tUInt8 DEF_y__h4401;
  tUInt8 DEF_x__h4400;
  tUInt8 DEF_y__h5285;
  tUInt8 DEF_y__h4399;
  tUInt8 DEF_x__h4398;
  tUInt8 DEF_y__h5408;
  tUInt8 DEF_y__h4397;
  tUInt8 DEF_x__h4396;
  tUInt8 DEF_cout__h4382;
  tUInt8 DEF_y__h5068;
  tUInt8 DEF_x__h5067;
  tUInt8 DEF_y__h5066;
  tUInt8 DEF_x__h5065;
  tUInt8 DEF_y__h5283;
  tUInt8 DEF_x__h5282;
  tUInt8 DEF_y__h5518;
  tUInt8 DEF_y__h6092;
  tUInt8 DEF_y__h5516;
  tUInt8 DEF_x__h5515;
  tUInt8 DEF_y__h6298;
  tUInt8 DEF_y__h5514;
  tUInt8 DEF_x__h5513;
  tUInt8 DEF_cout__h5497;
  tUInt8 DEF_y__h6090;
  tUInt8 DEF_x__h6089;
  tUInt8 DEF_y__h6524;
  tUInt8 DEF_x__h6523;
  tUInt8 DEF_y__h7072;
  tUInt8 DEF_y__h6710;
  tUInt8 DEF_y__h6522;
  tUInt8 DEF_x__h6521;
  tUInt8 DEF_y__h7278;
  tUInt8 DEF_y__h6755;
  tUInt8 DEF_y__h6520;
  tUInt8 DEF_x__h6519;
  tUInt8 DEF_y__h6819;
  tUInt8 DEF_y__h6518;
  tUInt8 DEF_x__h6517;
  tUInt8 DEF_cout__h6503;
  tUInt8 DEF_y__h7070;
  tUInt8 DEF_x__h7069;
  tUInt8 DEF_y__h7068;
  tUInt8 DEF_x__h7067;
  tUInt8 DEF_y__h7276;
  tUInt8 DEF_x__h7275;
  tUInt8 DEF_y__h7506;
  tUInt8 DEF_y__h7962;
  tUInt8 DEF_y__h7504;
  tUInt8 DEF_x__h7503;
  tUInt8 DEF_y__h8177;
  tUInt8 DEF_y__h7502;
  tUInt8 DEF_x__h7501;
  tUInt8 DEF_y__h8300;
  tUInt8 DEF_y__h7500;
  tUInt8 DEF_x__h7499;
  tUInt8 DEF_cout__h7485;
  tUInt8 DEF_y__h7960;
  tUInt8 DEF_x__h7959;
  tUInt8 DEF_y__h7958;
  tUInt8 DEF_x__h7957;
  tUInt8 DEF_y__h8175;
  tUInt8 DEF_x__h8174;
  tUInt8 DEF_x__h6709;
  tUInt8 DEF_y__h6757;
  tUInt8 DEF_y__h6821;
  tUInt8 DEF_y__h2762;
  tUInt8 DEF_sum__h2030;
  tUInt8 DEF_y__h3875;
  tUInt8 DEF_sum__h3268;
  tUInt8 DEF_y__h4990;
  tUInt8 DEF_sum__h4383;
  tUInt8 DEF_y__h6012;
  tUInt8 DEF_p__h5496;
  tUInt8 DEF_sum__h5498;
  tUInt8 DEF_rg_a__h7475;
  tUInt8 DEF_y__h7882;
  tUInt8 DEF_sum__h7486;
  tUInt8 DEF_y__h6906;
  tUInt8 DEF_x__h3780;
  tUInt8 DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_4_0_93___d194;
  tUInt8 DEF_x__h3361;
  tUInt8 DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_3_7_98___d199;
  tUInt8 DEF_x__h2667;
  tUInt8 DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_2_1_06___d207;
  tUInt8 DEF_x__h2247;
  tUInt8 DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_1_14___d215;
  tUInt8 DEF_x__h4895;
  tUInt8 DEF_x__h2120;
  tUInt8 DEF_x__h8513;
  tUInt8 DEF_x__h4476;
  tUInt8 DEF_x__h8870;
  tUInt8 DEF_x__h5656;
  tUInt8 DEF_y__h5658;
  tUInt8 DEF_y__h5840;
  tUInt8 DEF_y__h5776;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d162;
  tUInt8 DEF_x__h5728;
  tUInt8 DEF_y__h5774;
  tUInt8 DEF_y__h5729;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d160;
  tUInt8 DEF_x__h5517;
  tUInt8 DEF_y__h2546;
  tUInt8 DEF_y__h2457;
  tUInt8 DEF_y__h2390;
  tUInt8 DEF_p__h2028;
  tUInt8 DEF_x__h2342;
  tUInt8 DEF_y__h2455;
  tUInt8 DEF_y__h2388;
  tUInt8 DEF_y__h2343;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0_ETC___d12;
  tUInt8 DEF_x__h2049;
  tUInt8 DEF_y__h3569;
  tUInt8 DEF_y__h3502;
  tUInt8 DEF_y__h3457;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d61;
  tUInt8 DEF_x__h3287;
  tUInt8 DEF_y__h3660;
  tUInt8 DEF_y__h3571;
  tUInt8 DEF_y__h3504;
  tUInt8 DEF_p__h3266;
  tUInt8 DEF_x__h3456;
  tUInt8 DEF_y__h4684;
  tUInt8 DEF_y__h4617;
  tUInt8 DEF_y__h4572;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d110;
  tUInt8 DEF_x__h4402;
  tUInt8 DEF_y__h4775;
  tUInt8 DEF_y__h4686;
  tUInt8 DEF_y__h4619;
  tUInt8 DEF_p__h4381;
  tUInt8 DEF_x__h4571;
  tUInt8 DEF_y__h7682;
  tUInt8 DEF_y__h7615;
  tUInt8 DEF_y__h7570;
  tUInt8 DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_6_29__ETC___d247;
  tUInt8 DEF_x__h7505;
  tUInt8 DEF_y__h7773;
  tUInt8 DEF_y__h7684;
  tUInt8 DEF_y__h7617;
  tUInt8 DEF_p__h7484;
  tUInt8 DEF_x__h7569;
  tUInt8 DEF_x__h8462;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_1_ETC___d175;
  tUInt8 DEF_x__h8564;
  tUInt8 DEF_x__h8360;
  tUInt8 DEF_x__h8411;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0_ETC___d174;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d34;
  tUInt8 DEF_x__h8615;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d216;
  tUInt8 DEF_x__h8666;
  tUInt8 DEF_x__h8717;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_3_ETC___d208;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d83;
  tUInt8 DEF_x__h8768;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d200;
  tUInt8 DEF_x__h8819;
  tUInt8 DEF_cin__h7477;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_5_ETC___d195;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d132;
  tUInt8 DEF_x__h2192;
  tUInt8 DEF_x__h2317;
  tUInt8 DEF_x__h2737;
  tUInt8 DEF_x__h3431;
  tUInt8 DEF_x__h3850;
  tUInt8 DEF_x__h4546;
  tUInt8 DEF_x__h4965;
  tUInt8 DEF_x__h5682;
  tUInt8 DEF_obj_mac_x_BIT_7___h5623;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d154;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d131;
  tUInt8 DEF_INV_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_B_ETC___d159;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_1___d10;
  tUInt8 DEF_rg_b__h2020;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0___d6;
  tUInt8 DEF_rg_a__h2019;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d33;
  tUInt8 DEF_rg_a__h3257;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_3_ETC___d59;
  tUInt8 DEF_rg_b__h3258;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d82;
  tUInt8 DEF_rg_a__h4372;
  tUInt8 DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_5_ETC___d108;
  tUInt8 DEF_rg_b__h4373;
  tUInt8 DEF_INV_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_B_ETC___d158;
  tUInt8 DEF_rg_b__h7476;
  tUInt8 DEF_x__h5657;
  tUInt8 DEF_obj_mac_x__h5679;
  tUInt8 DEF_obj_mac_y__h5703;
  DEF_obj_mac_y__h5703 = INST_obj_mac_y.METH_read();
  DEF_obj_mac_x__h5679 = INST_obj_mac_x.METH_read();
  DEF_x__h5657 = (tUInt8)((tUInt8)127u & DEF_obj_mac_x__h5679);
  DEF_obj_mac_x_BIT_7___h5623 = (tUInt8)(DEF_obj_mac_x__h5679 >> 7u);
  DEF_x__h5682 = (tUInt8)(DEF_obj_mac_y__h5703 >> 7u);
  DEF_x__h4965 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_y__h5703 >> 6u));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d131 = DEF_x__h5657 & primSignExt8(7u,
											      1u,
											      (tUInt8)(DEF_x__h4965));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d154 = (tUInt8)((tUInt8)7u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d131 >> 1u));
  DEF_x__h4546 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_y__h5703 >> 5u));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_5_ETC___d108 = DEF_x__h5657 & primSignExt8(7u,
											      1u,
											      (tUInt8)(DEF_x__h4546));
  DEF_rg_b__h4373 = (tUInt8)((tUInt8)15u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_5_ETC___d108 >> 1u));
  DEF_x__h3850 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_y__h5703 >> 4u));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d82 = DEF_x__h5657 & primSignExt8(7u,
											     1u,
											     (tUInt8)(DEF_x__h3850));
  DEF_rg_a__h4372 = (tUInt8)((tUInt8)15u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d82 >> 2u));
  DEF_x__h3431 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_y__h5703 >> 3u));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_3_ETC___d59 = DEF_x__h5657 & primSignExt8(7u,
											     1u,
											     (tUInt8)(DEF_x__h3431));
  DEF_rg_b__h3258 = (tUInt8)((tUInt8)15u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_3_ETC___d59 >> 1u));
  DEF_x__h2737 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_y__h5703 >> 2u));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d33 = DEF_x__h5657 & primSignExt8(7u,
											     1u,
											     (tUInt8)(DEF_x__h2737));
  DEF_rg_a__h3257 = (tUInt8)((tUInt8)15u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d33 >> 2u));
  DEF_x__h2317 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_y__h5703 >> 1u));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_1___d10 = DEF_x__h5657 & primSignExt8(7u,
											 1u,
											 (tUInt8)(DEF_x__h2317));
  DEF_rg_b__h2020 = (tUInt8)((tUInt8)15u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_1___d10 >> 1u));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d132 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d131);
  DEF_x__h2192 = (tUInt8)((tUInt8)1u & DEF_obj_mac_y__h5703);
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0___d6 = DEF_x__h5657 & primSignExt8(7u,
											1u,
											(tUInt8)(DEF_x__h2192));
  DEF_rg_a__h2019 = (tUInt8)((tUInt8)15u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0___d6 >> 2u));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_5_ETC___d195 = (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_5_ETC___d108 >> 6u);
  DEF_cin__h7477 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_5_ETC___d108 >> 5u));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d200 = (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d82 >> 6u);
  DEF_x__h8819 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_5_ETC___d108);
  DEF_x__h8768 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d82 >> 1u));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d83 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d82);
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_3_ETC___d208 = (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_3_ETC___d59 >> 6u);
  DEF_x__h8717 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_3_ETC___d59 >> 5u));
  DEF_x__h8666 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_3_ETC___d59);
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d34 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d33);
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d216 = (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d33 >> 6u);
  DEF_x__h8615 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d33 >> 1u));
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0_ETC___d174 = (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0___d6 >> 6u);
  DEF_x__h8411 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0___d6 >> 1u));
  DEF_x__h8360 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0___d6);
  DEF_x__h8564 = (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_1___d10 >> 6u);
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_1_ETC___d175 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_1___d10 >> 5u));
  DEF_x__h8462 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_1___d10);
  DEF_p__h4381 = DEF_rg_a__h4372 ^ DEF_rg_b__h4373;
  DEF_x__h4571 = (tUInt8)(DEF_p__h4381 >> 3u);
  DEF_y__h4619 = (tUInt8)((tUInt8)1u & (DEF_p__h4381 >> 2u));
  DEF_y__h4686 = (tUInt8)((tUInt8)1u & (DEF_p__h4381 >> 1u));
  DEF_y__h4775 = (tUInt8)((tUInt8)1u & DEF_p__h4381);
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d110 = DEF_rg_a__h4372 & DEF_rg_b__h4373;
  DEF_x__h4402 = (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d110 >> 3u);
  DEF_y__h4572 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d110 >> 2u));
  DEF_y__h4617 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d110 >> 1u));
  DEF_y__h4684 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d110);
  DEF_p__h3266 = DEF_rg_a__h3257 ^ DEF_rg_b__h3258;
  DEF_x__h3456 = (tUInt8)(DEF_p__h3266 >> 3u);
  DEF_y__h3504 = (tUInt8)((tUInt8)1u & (DEF_p__h3266 >> 2u));
  DEF_y__h3571 = (tUInt8)((tUInt8)1u & (DEF_p__h3266 >> 1u));
  DEF_y__h3660 = (tUInt8)((tUInt8)1u & DEF_p__h3266);
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d61 = DEF_rg_a__h3257 & DEF_rg_b__h3258;
  DEF_x__h3287 = (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d61 >> 3u);
  DEF_y__h3457 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d61 >> 2u));
  DEF_y__h3502 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d61 >> 1u));
  DEF_y__h3569 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d61);
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0_ETC___d12 = DEF_rg_a__h2019 & DEF_rg_b__h2020;
  DEF_x__h2049 = (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0_ETC___d12 >> 3u);
  DEF_y__h2343 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0_ETC___d12 >> 2u));
  DEF_y__h2388 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0_ETC___d12 >> 1u));
  DEF_y__h2455 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0_ETC___d12);
  DEF_p__h2028 = DEF_rg_a__h2019 ^ DEF_rg_b__h2020;
  DEF_x__h2342 = (tUInt8)(DEF_p__h2028 >> 3u);
  DEF_y__h2390 = (tUInt8)((tUInt8)1u & (DEF_p__h2028 >> 2u));
  DEF_y__h2457 = (tUInt8)((tUInt8)1u & (DEF_p__h2028 >> 1u));
  DEF_y__h2546 = (tUInt8)((tUInt8)1u & DEF_p__h2028);
  DEF_y__h5658 = primSignExt8(7u, 1u, (tUInt8)(DEF_x__h5682));
  DEF_x__h5656 = DEF_x__h5657 & DEF_y__h5658;
  DEF_INV_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_B_ETC___d158 = (tUInt8)127u & ~DEF_x__h5656;
  DEF_rg_b__h7476 = (tUInt8)(DEF_INV_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_B_ETC___d158 >> 3u);
  DEF_INV_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_B_ETC___d159 = (tUInt8)((tUInt8)7u & DEF_INV_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_B_ETC___d158);
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d160 = DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d154 & DEF_INV_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_B_ETC___d159;
  DEF_x__h5517 = (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d160 >> 2u);
  DEF_y__h5729 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d160 >> 1u));
  DEF_y__h5774 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d160);
  DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d162 = DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d154 ^ DEF_INV_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_B_ETC___d159;
  DEF_x__h5728 = (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d162 >> 2u);
  DEF_y__h5776 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d162 >> 1u));
  DEF_y__h5840 = (tUInt8)((tUInt8)1u & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d162);
  DEF_x__h4476 = DEF_obj_mac_x_BIT_7___h5623 & DEF_x__h4546;
  DEF_x__h8870 = (tUInt8)1u & ~DEF_x__h4476;
  DEF_x__h2120 = DEF_obj_mac_x_BIT_7___h5623 & DEF_x__h2192;
  DEF_x__h8513 = (tUInt8)1u & ~DEF_x__h2120;
  DEF_x__h4895 = DEF_obj_mac_x_BIT_7___h5623 & DEF_x__h4965;
  DEF_x__h2247 = DEF_obj_mac_x_BIT_7___h5623 & DEF_x__h2317;
  DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_1_14___d215 = (tUInt8)1u & ~DEF_x__h2247;
  DEF_x__h2667 = DEF_obj_mac_x_BIT_7___h5623 & DEF_x__h2737;
  DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_2_1_06___d207 = (tUInt8)1u & ~DEF_x__h2667;
  DEF_x__h3361 = DEF_obj_mac_x_BIT_7___h5623 & DEF_x__h3431;
  DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_3_7_98___d199 = (tUInt8)1u & ~DEF_x__h3361;
  DEF_x__h3780 = DEF_obj_mac_x_BIT_7___h5623 & DEF_x__h3850;
  DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_4_0_93___d194 = (tUInt8)1u & ~DEF_x__h3780;
  DEF_y__h6906 = DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_1_14___d215 ^ DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d216;
  DEF_rg_a__h7475 = (tUInt8)15u & ((((tUInt8)1u & ~DEF_x__h4895) << 3u) | (tUInt8)(DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d131 >> 4u));
  DEF_p__h7484 = DEF_rg_a__h7475 ^ DEF_rg_b__h7476;
  DEF_x__h7569 = (tUInt8)(DEF_p__h7484 >> 3u);
  DEF_y__h7617 = (tUInt8)((tUInt8)1u & (DEF_p__h7484 >> 2u));
  DEF_y__h7684 = (tUInt8)((tUInt8)1u & (DEF_p__h7484 >> 1u));
  DEF_y__h7773 = (tUInt8)((tUInt8)1u & DEF_p__h7484);
  DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_6_29__ETC___d247 = DEF_rg_a__h7475 & DEF_rg_b__h7476;
  DEF_x__h7505 = (tUInt8)(DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_6_29__ETC___d247 >> 3u);
  DEF_y__h7570 = (tUInt8)((tUInt8)1u & (DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_6_29__ETC___d247 >> 2u));
  DEF_y__h7615 = (tUInt8)((tUInt8)1u & (DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_6_29__ETC___d247 >> 1u));
  DEF_y__h7682 = (tUInt8)((tUInt8)1u & DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_6_29__ETC___d247);
  DEF_p__h5496 = (tUInt8)15u & ((DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d162 << 1u) | (DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0_ETC___d174 ^ DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_1_ETC___d175));
  DEF_y__h6821 = DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_2_1_06___d207 ^ DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_3_ETC___d208;
  DEF_y__h6757 = DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_3_7_98___d199 ^ DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d200;
  DEF_x__h6709 = DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_4_0_93___d194 ^ DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_5_ETC___d195;
  DEF_y__h8300 = DEF_y__h7773 & DEF_cin__h7477;
  DEF_y__h8177 = DEF_y__h7684 & DEF_y__h7682;
  DEF_x__h8174 = DEF_y__h7615 | DEF_y__h8177;
  DEF_y__h7962 = DEF_y__h7617 & DEF_y__h7615;
  DEF_x__h7959 = DEF_y__h7570 | DEF_y__h7962;
  DEF_y__h7506 = DEF_x__h7569 & DEF_y__h7570;
  DEF_x__h7503 = DEF_x__h7505 | DEF_y__h7506;
  DEF_y__h7276 = DEF_y__h6821 & DEF_y__h6906;
  DEF_y__h6819 = DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_1_14___d215 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d216;
  DEF_y__h6755 = DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_2_1_06___d207 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_3_ETC___d208;
  DEF_y__h7278 = DEF_y__h6821 & DEF_y__h6819;
  DEF_x__h7275 = DEF_y__h6755 | DEF_y__h7278;
  DEF_y__h6710 = DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_3_7_98___d199 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d200;
  DEF_y__h7072 = DEF_y__h6757 & DEF_y__h6755;
  DEF_x__h7069 = DEF_y__h6710 | DEF_y__h7072;
  DEF_x__h6523 = DEF_INV_obj_mac_x_BIT_7_92_AND_obj_mac_y_BIT_4_0_93___d194 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_5_ETC___d195;
  DEF_y__h6524 = DEF_x__h6709 & DEF_y__h6710;
  DEF_x__h6521 = DEF_x__h6523 | DEF_y__h6524;
  DEF_y__h6092 = DEF_y__h5776 & DEF_y__h5774;
  DEF_x__h6089 = DEF_y__h5729 | DEF_y__h6092;
  DEF_y__h5518 = DEF_x__h5728 & DEF_y__h5729;
  DEF_x__h5515 = DEF_x__h5517 | DEF_y__h5518;
  DEF_y__h5408 = DEF_y__h4775 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d132;
  DEF_y__h5285 = DEF_y__h4686 & DEF_y__h4684;
  DEF_x__h5282 = DEF_y__h4617 | DEF_y__h5285;
  DEF_y__h5070 = DEF_y__h4619 & DEF_y__h4617;
  DEF_x__h5067 = DEF_y__h4572 | DEF_y__h5070;
  DEF_y__h4403 = DEF_x__h4571 & DEF_y__h4572;
  DEF_x__h4400 = DEF_x__h4402 | DEF_y__h4403;
  DEF_y__h4293 = DEF_y__h3660 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d83;
  DEF_y__h4170 = DEF_y__h3571 & DEF_y__h3569;
  DEF_x__h4167 = DEF_y__h3502 | DEF_y__h4170;
  DEF_y__h3955 = DEF_y__h3504 & DEF_y__h3502;
  DEF_x__h3952 = DEF_y__h3457 | DEF_y__h3955;
  DEF_y__h3288 = DEF_x__h3456 & DEF_y__h3457;
  DEF_x__h3285 = DEF_x__h3287 | DEF_y__h3288;
  DEF_y__h3180 = DEF_y__h2546 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d34;
  DEF_y__h3057 = DEF_y__h2457 & DEF_y__h2455;
  DEF_x__h3054 = DEF_y__h2388 | DEF_y__h3057;
  DEF_y__h2050 = DEF_x__h2342 & DEF_y__h2343;
  DEF_x__h2047 = DEF_x__h2049 | DEF_y__h2050;
  DEF_y__h2842 = DEF_y__h2390 & DEF_y__h2388;
  DEF_x__h2839 = DEF_y__h2343 | DEF_y__h2842;
  DEF_x__h8244 = DEF_y__h7684 & DEF_y__h7773;
  DEF_y__h8175 = DEF_x__h8244 & DEF_cin__h7477;
  DEF_x__h8029 = DEF_y__h7617 & DEF_y__h7684;
  DEF_y__h7960 = DEF_x__h8029 & DEF_y__h7682;
  DEF_x__h7957 = DEF_x__h7959 | DEF_y__h7960;
  DEF_x__h8096 = DEF_x__h8029 & DEF_y__h7773;
  DEF_y__h7958 = DEF_x__h8096 & DEF_cin__h7477;
  DEF_y__h7882 = (tUInt8)15u & (((((DEF_x__h7957 | DEF_y__h7958) << 3u) | ((DEF_x__h8174 | DEF_y__h8175) << 2u)) | ((DEF_y__h7682 | DEF_y__h8300) << 1u)) | DEF_cin__h7477);
  DEF_sum__h7486 = DEF_p__h7484 ^ DEF_y__h7882;
  DEF_x__h7614 = DEF_x__h7569 & DEF_y__h7617;
  DEF_y__h7504 = DEF_x__h7614 & DEF_y__h7615;
  DEF_x__h7501 = DEF_x__h7503 | DEF_y__h7504;
  DEF_x__h7681 = DEF_x__h7614 & DEF_y__h7684;
  DEF_y__h7502 = DEF_x__h7681 & DEF_y__h7682;
  DEF_x__h7499 = DEF_x__h7501 | DEF_y__h7502;
  DEF_x__h7771 = DEF_x__h7681 & DEF_y__h7773;
  DEF_y__h7500 = DEF_x__h7771 & DEF_cin__h7477;
  DEF_cout__h7485 = DEF_x__h7499 | DEF_y__h7500;
  DEF_x__h7136 = DEF_y__h6757 & DEF_y__h6821;
  DEF_y__h7068 = DEF_x__h7136 & DEF_y__h6906;
  DEF_y__h7070 = DEF_x__h7136 & DEF_y__h6819;
  DEF_x__h7067 = DEF_x__h7069 | DEF_y__h7070;
  DEF_x__h6754 = DEF_x__h6709 & DEF_y__h6757;
  DEF_y__h6522 = DEF_x__h6754 & DEF_y__h6755;
  DEF_x__h6519 = DEF_x__h6521 | DEF_y__h6522;
  DEF_x__h6818 = DEF_x__h6754 & DEF_y__h6821;
  DEF_y__h6518 = DEF_x__h6818 & DEF_y__h6906;
  DEF_y__h6520 = DEF_x__h6818 & DEF_y__h6819;
  DEF_x__h6517 = DEF_x__h6519 | DEF_y__h6520;
  DEF_cout__h6503 = DEF_x__h6517 | DEF_y__h6518;
  DEF_x__h8912 = DEF_obj_mac_x_BIT_7___h5623 & DEF_x__h5682;
  DEF_x__h5352 = DEF_y__h4686 & DEF_y__h4775;
  DEF_y__h5283 = DEF_x__h5352 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d132;
  DEF_x__h6156 = DEF_y__h5776 & DEF_y__h5840;
  DEF_y__h5838 = DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_0_ETC___d174 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_1_ETC___d175;
  DEF_y__h6090 = DEF_x__h6156 & DEF_y__h5838;
  DEF_y__h6298 = DEF_y__h5840 & DEF_y__h5838;
  DEF_y__h6012 = (tUInt8)15u & ((((DEF_x__h6089 | DEF_y__h6090) << 3u) | ((DEF_y__h5774 | DEF_y__h6298) << 2u)) | (DEF_y__h5838 << 1u));
  DEF_sum__h5498 = DEF_p__h5496 ^ DEF_y__h6012;
  DEF_x__h5773 = DEF_x__h5728 & DEF_y__h5776;
  DEF_y__h5516 = DEF_x__h5773 & DEF_y__h5774;
  DEF_x__h5513 = DEF_x__h5515 | DEF_y__h5516;
  DEF_x__h5837 = DEF_x__h5773 & DEF_y__h5840;
  DEF_y__h5514 = DEF_x__h5837 & DEF_y__h5838;
  DEF_cout__h5497 = DEF_x__h5513 | DEF_y__h5514;
  DEF_x__h5137 = DEF_y__h4619 & DEF_y__h4686;
  DEF_y__h5068 = DEF_x__h5137 & DEF_y__h4684;
  DEF_x__h5065 = DEF_x__h5067 | DEF_y__h5068;
  DEF_x__h5204 = DEF_x__h5137 & DEF_y__h4775;
  DEF_y__h5066 = DEF_x__h5204 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d132;
  DEF_y__h4990 = (tUInt8)15u & (((((DEF_x__h5065 | DEF_y__h5066) << 3u) | ((DEF_x__h5282 | DEF_y__h5283) << 2u)) | ((DEF_y__h4684 | DEF_y__h5408) << 1u)) | DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d132);
  DEF_sum__h4383 = DEF_p__h4381 ^ DEF_y__h4990;
  DEF_x__h4616 = DEF_x__h4571 & DEF_y__h4619;
  DEF_y__h4401 = DEF_x__h4616 & DEF_y__h4617;
  DEF_x__h4398 = DEF_x__h4400 | DEF_y__h4401;
  DEF_x__h4683 = DEF_x__h4616 & DEF_y__h4686;
  DEF_y__h4399 = DEF_x__h4683 & DEF_y__h4684;
  DEF_x__h4396 = DEF_x__h4398 | DEF_y__h4399;
  DEF_x__h4773 = DEF_x__h4683 & DEF_y__h4775;
  DEF_y__h4397 = DEF_x__h4773 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_6_ETC___d132;
  DEF_cout__h4382 = DEF_x__h4396 | DEF_y__h4397;
  DEF_x__h4237 = DEF_y__h3571 & DEF_y__h3660;
  DEF_y__h4168 = DEF_x__h4237 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d83;
  DEF_x__h4022 = DEF_y__h3504 & DEF_y__h3571;
  DEF_y__h3953 = DEF_x__h4022 & DEF_y__h3569;
  DEF_x__h3950 = DEF_x__h3952 | DEF_y__h3953;
  DEF_x__h4089 = DEF_x__h4022 & DEF_y__h3660;
  DEF_y__h3951 = DEF_x__h4089 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d83;
  DEF_y__h3875 = (tUInt8)15u & (((((DEF_x__h3950 | DEF_y__h3951) << 3u) | ((DEF_x__h4167 | DEF_y__h4168) << 2u)) | ((DEF_y__h3569 | DEF_y__h4293) << 1u)) | DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d83);
  DEF_sum__h3268 = DEF_p__h3266 ^ DEF_y__h3875;
  DEF_x__h3501 = DEF_x__h3456 & DEF_y__h3504;
  DEF_y__h3286 = DEF_x__h3501 & DEF_y__h3502;
  DEF_x__h3283 = DEF_x__h3285 | DEF_y__h3286;
  DEF_x__h3568 = DEF_x__h3501 & DEF_y__h3571;
  DEF_y__h3284 = DEF_x__h3568 & DEF_y__h3569;
  DEF_x__h3281 = DEF_x__h3283 | DEF_y__h3284;
  DEF_x__h3658 = DEF_x__h3568 & DEF_y__h3660;
  DEF_y__h3282 = DEF_x__h3658 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_4_ETC___d83;
  DEF_cout__h3267 = DEF_x__h3281 | DEF_y__h3282;
  DEF_x__h3124 = DEF_y__h2457 & DEF_y__h2546;
  DEF_y__h3055 = DEF_x__h3124 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d34;
  DEF_x__h2909 = DEF_y__h2390 & DEF_y__h2457;
  DEF_y__h2840 = DEF_x__h2909 & DEF_y__h2455;
  DEF_x__h2837 = DEF_x__h2839 | DEF_y__h2840;
  DEF_x__h2976 = DEF_x__h2909 & DEF_y__h2546;
  DEF_y__h2838 = DEF_x__h2976 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d34;
  DEF_y__h2762 = (tUInt8)15u & (((((DEF_x__h2837 | DEF_y__h2838) << 3u) | ((DEF_x__h3054 | DEF_y__h3055) << 2u)) | ((DEF_y__h2455 | DEF_y__h3180) << 1u)) | DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d34);
  DEF_sum__h2030 = DEF_p__h2028 ^ DEF_y__h2762;
  DEF_x__h2387 = DEF_x__h2342 & DEF_y__h2390;
  DEF_y__h2048 = DEF_x__h2387 & DEF_y__h2388;
  DEF_x__h2045 = DEF_x__h2047 | DEF_y__h2048;
  DEF_x__h2454 = DEF_x__h2387 & DEF_y__h2457;
  DEF_y__h2046 = DEF_x__h2454 & DEF_y__h2455;
  DEF_x__h2043 = DEF_x__h2045 | DEF_y__h2046;
  DEF_x__h7456 = (tUInt8)31u & ((DEF_cout__h7485 << 4u) | DEF_sum__h7486);
  DEF_x__h2544 = DEF_x__h2454 & DEF_y__h2546;
  DEF_y__h2044 = DEF_x__h2544 & DEF_obj_mac_x_BITS_6_TO_0_AND_SEXT_obj_mac_y_BIT_2_ETC___d34;
  DEF_cout__h2029 = DEF_x__h2043 | DEF_y__h2044;
  DEF_sum__h6504 = (tUInt8)15u & (((((DEF_x__h6709 ^ (DEF_x__h7067 | DEF_y__h7068)) << 3u) | ((DEF_y__h6757 ^ (DEF_x__h7275 | DEF_y__h7276)) << 2u)) | ((DEF_y__h6821 ^ (DEF_y__h6819 | DEF_y__h6906)) << 1u)) | ((tUInt8)1u & ~DEF_y__h6906));
  DEF_x__h6474 = (tUInt8)31u & ((DEF_cout__h6503 << 4u) | DEF_sum__h6504);
  DEF_x__h5468 = (tUInt8)31u & ((DEF_cout__h5497 << 4u) | DEF_sum__h5498);
  DEF_x__h4353 = (tUInt8)31u & ((DEF_cout__h4382 << 4u) | DEF_sum__h4383);
  DEF_x__h2000 = (tUInt8)31u & ((DEF_cout__h2029 << 4u) | DEF_sum__h2030);
  DEF_x__h3238 = (tUInt8)31u & ((DEF_cout__h3267 << 4u) | DEF_sum__h3268);
  INST_obj_mac_s11.METH_write(DEF_x__h2000);
  INST_obj_mac_s12.METH_write(DEF_x__h3238);
  INST_obj_mac_s13.METH_write(DEF_x__h4353);
  INST_obj_mac_s14.METH_write(DEF_x__h5468);
  INST_obj_mac_s15.METH_write(DEF_x__h6474);
  INST_obj_mac_s16.METH_write(DEF_x__h7456);
  INST_obj_mac_pp00.METH_write(DEF_x__h8360);
  INST_obj_mac_pp01.METH_write(DEF_x__h8411);
  INST_obj_mac_pp10.METH_write(DEF_x__h8462);
  INST_obj_mac_pp07.METH_write(DEF_x__h8513);
  INST_obj_mac_pp16.METH_write(DEF_x__h8564);
  INST_obj_mac_pp21.METH_write(DEF_x__h8615);
  INST_obj_mac_pp30.METH_write(DEF_x__h8666);
  INST_obj_mac_pp35.METH_write(DEF_x__h8717);
  INST_obj_mac_pp41.METH_write(DEF_x__h8768);
  INST_obj_mac_pp50.METH_write(DEF_x__h8819);
  INST_obj_mac_pp57.METH_write(DEF_x__h8870);
  INST_obj_mac_pp77.METH_write(DEF_x__h8912);
}

void MOD_mk_Test::RL_obj_mac_stage2()
{
  tUInt8 DEF_x__h8951;
  tUInt8 DEF_x__h9841;
  tUInt8 DEF_x__h10707;
  tUInt8 DEF_x__h9115;
  tUInt8 DEF_x__h9182;
  tUInt8 DEF_x__h9272;
  tUInt8 DEF_x__h9512;
  tUInt8 DEF_x__h9579;
  tUInt8 DEF_x__h9727;
  tUInt8 DEF_x__h10007;
  tUInt8 DEF_x__h10071;
  tUInt8 DEF_y__h10072;
  tUInt8 DEF_x__h10389;
  tUInt8 DEF_x__h10915;
  tUInt8 DEF_x__h10979;
  tUInt8 DEF_x__h11065;
  tUInt8 DEF_x__h11298;
  tUInt8 DEF_x__h11362;
  tUInt8 DEF_x__h11504;
  tUInt8 DEF_y__h9001;
  tUInt8 DEF_y__h9445;
  tUInt8 DEF_y__h8999;
  tUInt8 DEF_x__h8998;
  tUInt8 DEF_y__h9660;
  tUInt8 DEF_y__h8997;
  tUInt8 DEF_x__h8996;
  tUInt8 DEF_y__h9783;
  tUInt8 DEF_y__h8995;
  tUInt8 DEF_x__h8994;
  tUInt8 DEF_cout__h8980;
  tUInt8 DEF_y__h9443;
  tUInt8 DEF_x__h9442;
  tUInt8 DEF_y__h9441;
  tUInt8 DEF_x__h9440;
  tUInt8 DEF_y__h9658;
  tUInt8 DEF_x__h9657;
  tUInt8 DEF_y__h9891;
  tUInt8 DEF_y__h10325;
  tUInt8 DEF_y__h9889;
  tUInt8 DEF_x__h9888;
  tUInt8 DEF_y__h10531;
  tUInt8 DEF_y__h9887;
  tUInt8 DEF_x__h9886;
  tUInt8 DEF_cout__h9870;
  tUInt8 DEF_y__h10323;
  tUInt8 DEF_x__h10322;
  tUInt8 DEF_y__h10757;
  tUInt8 DEF_y__h11234;
  tUInt8 DEF_y__h10755;
  tUInt8 DEF_x__h10754;
  tUInt8 DEF_y__h11440;
  tUInt8 DEF_y__h10753;
  tUInt8 DEF_x__h10752;
  tUInt8 DEF_y__h11558;
  tUInt8 DEF_y__h10751;
  tUInt8 DEF_x__h10750;
  tUInt8 DEF_cout__h10736;
  tUInt8 DEF_y__h11232;
  tUInt8 DEF_x__h11231;
  tUInt8 DEF_y__h11230;
  tUInt8 DEF_x__h11229;
  tUInt8 DEF_y__h11438;
  tUInt8 DEF_x__h11437;
  tUInt8 DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98___d399;
  tUInt8 DEF_rg_b__h8971;
  tUInt8 DEF_y__h9365;
  tUInt8 DEF_sum__h8981;
  tUInt8 DEF_y__h10245;
  tUInt8 DEF_p__h9869;
  tUInt8 DEF_sum__h9871;
  tUInt8 DEF_y__h11154;
  tUInt8 DEF_p__h10735;
  tUInt8 DEF_sum__h10737;
  tUInt8 DEF_y__h10918;
  tUInt8 DEF_obj_mac_s13_49_BITS_4_TO_3_85_XOR_obj_mac_s14__ETC___d389;
  tUInt8 DEF_x__h10870;
  tUInt8 DEF_y__h10871;
  tUInt8 DEF_obj_mac_s13_49_BITS_4_TO_3_85_AND_obj_mac_s14__ETC___d387;
  tUInt8 DEF_x__h10756;
  tUInt8 DEF_y__h10980;
  tUInt8 DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98_ETC___d401;
  tUInt8 DEF_y__h10916;
  tUInt8 DEF_y__h11067;
  tUInt8 DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98_ETC___d405;
  tUInt8 DEF_y__h10982;
  tUInt8 DEF_y__h10008;
  tUInt8 DEF_y__h9963;
  tUInt8 DEF_obj_mac_s13_49_BITS_2_TO_0_50_AND_obj_mac_s14__ETC___d353;
  tUInt8 DEF_x__h9890;
  tUInt8 DEF_y__h10074;
  tUInt8 DEF_y__h10010;
  tUInt8 DEF_obj_mac_s13_49_BITS_2_TO_0_50_XOR_obj_mac_s14__ETC___d355;
  tUInt8 DEF_x__h9962;
  tUInt8 DEF_y__h9183;
  tUInt8 DEF_y__h9116;
  tUInt8 DEF_y__h9071;
  tUInt8 DEF_obj_mac_s11_02_BITS_4_TO_1_03_AND_obj_mac_s12__ETC___d308;
  tUInt8 DEF_x__h9000;
  tUInt8 DEF_y__h9274;
  tUInt8 DEF_y__h9185;
  tUInt8 DEF_y__h9118;
  tUInt8 DEF_p__h8979;
  tUInt8 DEF_x__h9070;
  tUInt8 DEF_obj_mac_s15_BIT_0___h10823;
  tUInt8 DEF_obj_mac_s12_BITS_4_TO_3___h10867;
  tUInt8 DEF_obj_mac_s13_BITS_4_TO_3___h10800;
  tUInt8 DEF_obj_mac_s14_BITS_4_TO_3___h10846;
  tUInt8 DEF_obj_mac_s12_BITS_2_TO_0___h9067;
  tUInt8 DEF_obj_mac_s13_BITS_2_TO_0___h9935;
  tUInt8 DEF_obj_mac_s14_BITS_2_TO_0___h9958;
  tUInt8 DEF_rg_a__h8970;
  tUInt8 DEF_x__h11616;
  tUInt8 DEF_x__h11649;
  tUInt8 DEF_x__h11682;
  tUInt8 DEF__read__h426;
  tUInt8 DEF_obj_mac_pp16___d413;
  tUInt8 DEF__read__h492;
  tUInt8 DEF_obj_mac_pp30___d327;
  tUInt8 DEF_x__h11715;
  tUInt8 DEF__read__h591;
  tUInt8 DEF__read__h624;
  tUInt8 DEF_x__h11748;
  tUInt8 DEF_x__h11781;
  tUInt8 DEF_x__h11846;
  tUInt8 DEF_obj_mac_s12___d304;
  tUInt8 DEF_obj_mac_s13___d349;
  tUInt8 DEF_obj_mac_s14___d351;
  tUInt8 DEF_x__h11814;
  DEF_x__h11869 = INST_obj_mac_s16.METH_read();
  DEF_x__h11814 = INST_obj_mac_s15.METH_read();
  DEF_obj_mac_s14___d351 = INST_obj_mac_s14.METH_read();
  DEF_obj_mac_s13___d349 = INST_obj_mac_s13.METH_read();
  DEF_obj_mac_s12___d304 = INST_obj_mac_s12.METH_read();
  DEF_x__h11846 = INST_obj_mac_s11.METH_read();
  DEF_x__h11781 = INST_obj_mac_pp77.METH_read();
  DEF_x__h11748 = INST_obj_mac_pp57.METH_read();
  DEF__read__h624 = INST_obj_mac_pp50.METH_read();
  DEF__read__h591 = INST_obj_mac_pp41.METH_read();
  DEF_obj_mac_pp30___d327 = INST_obj_mac_pp30.METH_read();
  DEF_x__h11715 = INST_obj_mac_pp35.METH_read();
  DEF__read__h492 = INST_obj_mac_pp21.METH_read();
  DEF_obj_mac_pp16___d413 = INST_obj_mac_pp16.METH_read();
  DEF__read__h426 = INST_obj_mac_pp07.METH_read();
  DEF_x__h11682 = INST_obj_mac_pp10.METH_read();
  DEF_x__h11649 = INST_obj_mac_pp01.METH_read();
  DEF_x__h11616 = INST_obj_mac_pp00.METH_read();
  DEF_rg_a__h8970 = (tUInt8)(DEF_x__h11846 >> 1u);
  DEF_obj_mac_s14_BITS_2_TO_0___h9958 = (tUInt8)((tUInt8)7u & DEF_obj_mac_s14___d351);
  DEF_obj_mac_s13_BITS_2_TO_0___h9935 = (tUInt8)((tUInt8)7u & DEF_obj_mac_s13___d349);
  DEF_obj_mac_s12_BITS_2_TO_0___h9067 = (tUInt8)((tUInt8)7u & DEF_obj_mac_s12___d304);
  DEF_obj_mac_s14_BITS_4_TO_3___h10846 = (tUInt8)(DEF_obj_mac_s14___d351 >> 3u);
  DEF_obj_mac_s13_BITS_4_TO_3___h10800 = (tUInt8)(DEF_obj_mac_s13___d349 >> 3u);
  DEF_obj_mac_s12_BITS_4_TO_3___h10867 = (tUInt8)(DEF_obj_mac_s12___d304 >> 3u);
  DEF_obj_mac_s15_BIT_0___h10823 = (tUInt8)((tUInt8)1u & DEF_x__h11814);
  DEF_obj_mac_s13_49_BITS_2_TO_0_50_XOR_obj_mac_s14__ETC___d355 = DEF_obj_mac_s13_BITS_2_TO_0___h9935 ^ DEF_obj_mac_s14_BITS_2_TO_0___h9958;
  DEF_x__h9962 = (tUInt8)(DEF_obj_mac_s13_49_BITS_2_TO_0_50_XOR_obj_mac_s14__ETC___d355 >> 2u);
  DEF_y__h10010 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_s13_49_BITS_2_TO_0_50_XOR_obj_mac_s14__ETC___d355 >> 1u));
  DEF_y__h10074 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s13_49_BITS_2_TO_0_50_XOR_obj_mac_s14__ETC___d355);
  DEF_obj_mac_s13_49_BITS_2_TO_0_50_AND_obj_mac_s14__ETC___d353 = DEF_obj_mac_s13_BITS_2_TO_0___h9935 & DEF_obj_mac_s14_BITS_2_TO_0___h9958;
  DEF_x__h9890 = (tUInt8)(DEF_obj_mac_s13_49_BITS_2_TO_0_50_AND_obj_mac_s14__ETC___d353 >> 2u);
  DEF_y__h9963 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_s13_49_BITS_2_TO_0_50_AND_obj_mac_s14__ETC___d353 >> 1u));
  DEF_y__h10008 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s13_49_BITS_2_TO_0_50_AND_obj_mac_s14__ETC___d353);
  DEF_obj_mac_s13_49_BITS_4_TO_3_85_AND_obj_mac_s14__ETC___d387 = DEF_obj_mac_s13_BITS_4_TO_3___h10800 & DEF_obj_mac_s14_BITS_4_TO_3___h10846;
  DEF_x__h10756 = (tUInt8)(DEF_obj_mac_s13_49_BITS_4_TO_3_85_AND_obj_mac_s14__ETC___d387 >> 1u);
  DEF_y__h10871 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s13_49_BITS_4_TO_3_85_AND_obj_mac_s14__ETC___d387);
  DEF_obj_mac_s13_49_BITS_4_TO_3_85_XOR_obj_mac_s14__ETC___d389 = DEF_obj_mac_s13_BITS_4_TO_3___h10800 ^ DEF_obj_mac_s14_BITS_4_TO_3___h10846;
  DEF_x__h10870 = (tUInt8)(DEF_obj_mac_s13_49_BITS_4_TO_3_85_XOR_obj_mac_s14__ETC___d389 >> 1u);
  DEF_y__h10918 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s13_49_BITS_4_TO_3_85_XOR_obj_mac_s14__ETC___d389);
  DEF_p__h9869 = (tUInt8)15u & ((DEF_obj_mac_s13_49_BITS_2_TO_0_50_XOR_obj_mac_s14__ETC___d355 << 1u) | (DEF__read__h591 ^ DEF__read__h624));
  DEF_rg_b__h8971 = (tUInt8)15u & ((DEF_obj_mac_s12_BITS_2_TO_0___h9067 << 1u) | DEF__read__h492);
  DEF_p__h8979 = DEF_rg_a__h8970 ^ DEF_rg_b__h8971;
  DEF_x__h9070 = (tUInt8)(DEF_p__h8979 >> 3u);
  DEF_y__h9118 = (tUInt8)((tUInt8)1u & (DEF_p__h8979 >> 2u));
  DEF_y__h9185 = (tUInt8)((tUInt8)1u & (DEF_p__h8979 >> 1u));
  DEF_y__h9274 = (tUInt8)((tUInt8)1u & DEF_p__h8979);
  DEF_obj_mac_s11_02_BITS_4_TO_1_03_AND_obj_mac_s12__ETC___d308 = DEF_rg_a__h8970 & DEF_rg_b__h8971;
  DEF_x__h9000 = (tUInt8)(DEF_obj_mac_s11_02_BITS_4_TO_1_03_AND_obj_mac_s12__ETC___d308 >> 3u);
  DEF_y__h9071 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_s11_02_BITS_4_TO_1_03_AND_obj_mac_s12__ETC___d308 >> 2u));
  DEF_y__h9116 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_s11_02_BITS_4_TO_1_03_AND_obj_mac_s12__ETC___d308 >> 1u));
  DEF_y__h9183 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s11_02_BITS_4_TO_1_03_AND_obj_mac_s12__ETC___d308);
  DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98___d399 = (tUInt8)3u & ((DEF_obj_mac_s15_BIT_0___h10823 << 1u) | DEF__read__h426);
  DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98_ETC___d405 = DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98___d399 ^ DEF_obj_mac_s12_BITS_4_TO_3___h10867;
  DEF_y__h10982 = (tUInt8)(DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98_ETC___d405 >> 1u);
  DEF_y__h11067 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98_ETC___d405);
  DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98_ETC___d401 = DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98___d399 & DEF_obj_mac_s12_BITS_4_TO_3___h10867;
  DEF_y__h10916 = (tUInt8)(DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98_ETC___d401 >> 1u);
  DEF_y__h10980 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98_ETC___d401);
  DEF_p__h10735 = (tUInt8)15u & ((DEF_obj_mac_s13_49_BITS_4_TO_3_85_XOR_obj_mac_s14__ETC___d389 << 2u) | DEF_obj_mac_s15_96_BIT_0_97_CONCAT_obj_mac_pp07_98_ETC___d405);
  DEF_y__h11558 = DEF_y__h11067 & DEF_obj_mac_pp16___d413;
  DEF_y__h11440 = DEF_y__h10982 & DEF_y__h10980;
  DEF_x__h11437 = DEF_y__h10916 | DEF_y__h11440;
  DEF_y__h11234 = DEF_y__h10918 & DEF_y__h10916;
  DEF_x__h11231 = DEF_y__h10871 | DEF_y__h11234;
  DEF_y__h10757 = DEF_x__h10870 & DEF_y__h10871;
  DEF_x__h10754 = DEF_x__h10756 | DEF_y__h10757;
  DEF_y__h10325 = DEF_y__h10010 & DEF_y__h10008;
  DEF_x__h10322 = DEF_y__h9963 | DEF_y__h10325;
  DEF_y__h9891 = DEF_x__h9962 & DEF_y__h9963;
  DEF_x__h9888 = DEF_x__h9890 | DEF_y__h9891;
  DEF_y__h9783 = DEF_y__h9274 & DEF_obj_mac_pp30___d327;
  DEF_y__h9660 = DEF_y__h9185 & DEF_y__h9183;
  DEF_x__h9657 = DEF_y__h9116 | DEF_y__h9660;
  DEF_x__h10915 = DEF_x__h10870 & DEF_y__h10918;
  DEF_y__h10755 = DEF_x__h10915 & DEF_y__h10916;
  DEF_x__h10752 = DEF_x__h10754 | DEF_y__h10755;
  DEF_y__h9445 = DEF_y__h9118 & DEF_y__h9116;
  DEF_x__h9442 = DEF_y__h9071 | DEF_y__h9445;
  DEF_y__h9001 = DEF_x__h9070 & DEF_y__h9071;
  DEF_x__h8998 = DEF_x__h9000 | DEF_y__h9001;
  DEF_x__h11504 = DEF_y__h10982 & DEF_y__h11067;
  DEF_y__h11438 = DEF_x__h11504 & DEF_obj_mac_pp16___d413;
  DEF_x__h11298 = DEF_y__h10918 & DEF_y__h10982;
  DEF_y__h11232 = DEF_x__h11298 & DEF_y__h10980;
  DEF_x__h11229 = DEF_x__h11231 | DEF_y__h11232;
  DEF_x__h11362 = DEF_x__h11298 & DEF_y__h11067;
  DEF_y__h11230 = DEF_x__h11362 & DEF_obj_mac_pp16___d413;
  DEF_y__h11154 = (tUInt8)15u & (((((DEF_x__h11229 | DEF_y__h11230) << 3u) | ((DEF_x__h11437 | DEF_y__h11438) << 2u)) | ((DEF_y__h10980 | DEF_y__h11558) << 1u)) | DEF_obj_mac_pp16___d413);
  DEF_sum__h10737 = DEF_p__h10735 ^ DEF_y__h11154;
  DEF_x__h10389 = DEF_y__h10010 & DEF_y__h10074;
  DEF_x__h10979 = DEF_x__h10915 & DEF_y__h10982;
  DEF_y__h10753 = DEF_x__h10979 & DEF_y__h10980;
  DEF_x__h10750 = DEF_x__h10752 | DEF_y__h10753;
  DEF_x__h11065 = DEF_x__h10979 & DEF_y__h11067;
  DEF_y__h10751 = DEF_x__h11065 & DEF_obj_mac_pp16___d413;
  DEF_cout__h10736 = DEF_x__h10750 | DEF_y__h10751;
  DEF_y__h10072 = DEF__read__h591 & DEF__read__h624;
  DEF_y__h10323 = DEF_x__h10389 & DEF_y__h10072;
  DEF_y__h10531 = DEF_y__h10074 & DEF_y__h10072;
  DEF_y__h10245 = (tUInt8)15u & ((((DEF_x__h10322 | DEF_y__h10323) << 3u) | ((DEF_y__h10008 | DEF_y__h10531) << 2u)) | (DEF_y__h10072 << 1u));
  DEF_sum__h9871 = DEF_p__h9869 ^ DEF_y__h10245;
  DEF_x__h10007 = DEF_x__h9962 & DEF_y__h10010;
  DEF_y__h9889 = DEF_x__h10007 & DEF_y__h10008;
  DEF_x__h9886 = DEF_x__h9888 | DEF_y__h9889;
  DEF_x__h10071 = DEF_x__h10007 & DEF_y__h10074;
  DEF_y__h9887 = DEF_x__h10071 & DEF_y__h10072;
  DEF_cout__h9870 = DEF_x__h9886 | DEF_y__h9887;
  DEF_x__h9727 = DEF_y__h9185 & DEF_y__h9274;
  DEF_y__h9658 = DEF_x__h9727 & DEF_obj_mac_pp30___d327;
  DEF_x__h9512 = DEF_y__h9118 & DEF_y__h9185;
  DEF_y__h9443 = DEF_x__h9512 & DEF_y__h9183;
  DEF_x__h9440 = DEF_x__h9442 | DEF_y__h9443;
  DEF_x__h9579 = DEF_x__h9512 & DEF_y__h9274;
  DEF_y__h9441 = DEF_x__h9579 & DEF_obj_mac_pp30___d327;
  DEF_y__h9365 = (tUInt8)15u & (((((DEF_x__h9440 | DEF_y__h9441) << 3u) | ((DEF_x__h9657 | DEF_y__h9658) << 2u)) | ((DEF_y__h9183 | DEF_y__h9783) << 1u)) | DEF_obj_mac_pp30___d327);
  DEF_sum__h8981 = DEF_p__h8979 ^ DEF_y__h9365;
  DEF_x__h9115 = DEF_x__h9070 & DEF_y__h9118;
  DEF_y__h8999 = DEF_x__h9115 & DEF_y__h9116;
  DEF_x__h8996 = DEF_x__h8998 | DEF_y__h8999;
  DEF_x__h9182 = DEF_x__h9115 & DEF_y__h9185;
  DEF_y__h8997 = DEF_x__h9182 & DEF_y__h9183;
  DEF_x__h8994 = DEF_x__h8996 | DEF_y__h8997;
  DEF_x__h9272 = DEF_x__h9182 & DEF_y__h9274;
  DEF_y__h8995 = DEF_x__h9272 & DEF_obj_mac_pp30___d327;
  DEF_cout__h8980 = DEF_x__h8994 | DEF_y__h8995;
  DEF_x__h10707 = (tUInt8)31u & ((DEF_cout__h10736 << 4u) | DEF_sum__h10737);
  DEF_x__h9841 = (tUInt8)31u & ((DEF_cout__h9870 << 4u) | DEF_sum__h9871);
  DEF_x__h8951 = (tUInt8)31u & ((DEF_cout__h8980 << 4u) | DEF_sum__h8981);
  INST_obj_mac_s21.METH_write(DEF_x__h8951);
  INST_obj_mac_s22.METH_write(DEF_x__h9841);
  INST_obj_mac_s23.METH_write(DEF_x__h10707);
  INST_obj_mac_pp00_s2.METH_write(DEF_x__h11616);
  INST_obj_mac_pp01_s2.METH_write(DEF_x__h11649);
  INST_obj_mac_pp10_s2.METH_write(DEF_x__h11682);
  INST_obj_mac_pp35_s2.METH_write(DEF_x__h11715);
  INST_obj_mac_pp57_s2.METH_write(DEF_x__h11748);
  INST_obj_mac_pp77_s2.METH_write(DEF_x__h11781);
  INST_obj_mac_s15_s2.METH_write(DEF_x__h11814);
  INST_obj_mac_s11_s2.METH_write(DEF_x__h11846);
  INST_obj_mac_s16_s2.METH_write(DEF_x__h11869);
}

void MOD_mk_Test::RL_obj_mac_stage3()
{
  tUInt8 DEF_x__h11902;
  tUInt8 DEF_x__h12053;
  tUInt8 DEF_x__h12230;
  tUInt8 DEF_x__h12427;
  tUInt8 DEF_x__h12624;
  tUInt8 DEF_x__h12820;
  tUInt8 DEF_y__h12196;
  tUInt8 DEF_x__h12195;
  tUInt8 DEF_y__h12393;
  tUInt8 DEF_x__h12392;
  tUInt8 DEF_y__h12590;
  tUInt8 DEF_x__h12589;
  tUInt8 DEF_y__h12786;
  tUInt8 DEF_x__h12785;
  tUInt8 DEF_y__h12962;
  tUInt8 DEF_x__h12961;
  tUInt8 DEF_x__h12139;
  tUInt8 DEF_x__h12316;
  tUInt8 DEF_x__h12513;
  tUInt8 DEF_x__h12710;
  tUInt8 DEF_x__h12906;
  tUInt8 DEF_a__h11942;
  tUInt8 DEF_b__h11943;
  tUInt8 DEF_b__h12093;
  tUInt8 DEF_b__h12270;
  tUInt8 DEF_cin__h12094;
  tUInt8 DEF_cin__h12271;
  tUInt8 DEF_cin__h12468;
  tUInt8 DEF_cin__h12665;
  tUInt8 DEF_a__h12269;
  tUInt8 DEF_a__h12466;
  tUInt8 DEF_a__h12663;
  tUInt8 DEF_a__h12859;
  tUInt8 DEF_b__h12467;
  tUInt8 DEF_b__h12664;
  tUInt8 DEF_b__h12860;
  tUInt8 DEF_x__h12996;
  tUInt8 DEF_x__h13062;
  tUInt8 DEF_x__h13029;
  tUInt8 DEF_a__h12092;
  tUInt8 DEF_cin__h12861;
  tUInt8 DEF_x__h13095;
  tUInt8 DEF_x__h13193;
  tUInt8 DEF_x__h13225;
  tUInt8 DEF_x__h13248;
  tUInt8 DEF_obj_mac_s15_s2__h12928;
  tUInt8 DEF_x__h13128;
  tUInt8 DEF_x__h13161;
  DEF_x__h13161 = INST_obj_mac_s16_s2.METH_read();
  DEF_x__h13128 = INST_obj_mac_s11_s2.METH_read();
  DEF_obj_mac_s15_s2__h12928 = INST_obj_mac_s15_s2.METH_read();
  DEF_x__h13248 = INST_obj_mac_s23.METH_read();
  DEF_x__h13225 = INST_obj_mac_s22.METH_read();
  DEF_x__h13193 = INST_obj_mac_s21.METH_read();
  DEF_x__h13095 = INST_obj_mac_pp77_s2.METH_read();
  DEF_cin__h12861 = INST_obj_mac_pp57_s2.METH_read();
  DEF_a__h12092 = INST_obj_mac_pp35_s2.METH_read();
  DEF_x__h13029 = INST_obj_mac_pp01_s2.METH_read();
  DEF_x__h13062 = INST_obj_mac_pp10_s2.METH_read();
  DEF_x__h12996 = INST_obj_mac_pp00_s2.METH_read();
  DEF_b__h12860 = (tUInt8)((tUInt8)1u & (DEF_x__h13161 >> 2u));
  DEF_b__h12664 = (tUInt8)((tUInt8)1u & (DEF_x__h13161 >> 1u));
  DEF_b__h12467 = (tUInt8)((tUInt8)1u & DEF_x__h13161);
  DEF_a__h12859 = (tUInt8)(DEF_obj_mac_s15_s2__h12928 >> 4u);
  DEF_a__h12663 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_s15_s2__h12928 >> 3u));
  DEF_a__h12466 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_s15_s2__h12928 >> 2u));
  DEF_a__h12269 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_s15_s2__h12928 >> 1u));
  DEF_cin__h12665 = (tUInt8)(DEF_x__h13248 >> 4u);
  DEF_cin__h12468 = (tUInt8)((tUInt8)1u & (DEF_x__h13248 >> 3u));
  DEF_cin__h12271 = (tUInt8)((tUInt8)1u & (DEF_x__h13248 >> 2u));
  DEF_cin__h12094 = (tUInt8)((tUInt8)1u & (DEF_x__h13248 >> 1u));
  DEF_b__h12270 = (tUInt8)(DEF_x__h13225 >> 4u);
  DEF_b__h12093 = (tUInt8)((tUInt8)1u & (DEF_x__h13225 >> 3u));
  DEF_b__h11943 = (tUInt8)((tUInt8)1u & (DEF_x__h13225 >> 2u));
  DEF_a__h11942 = (tUInt8)(DEF_x__h13193 >> 4u);
  DEF_x__h12906 = DEF_a__h12859 ^ DEF_b__h12860;
  DEF_x__h12710 = DEF_a__h12663 ^ DEF_b__h12664;
  DEF_x__h12513 = DEF_a__h12466 ^ DEF_b__h12467;
  DEF_x__h12316 = DEF_a__h12269 ^ DEF_b__h12270;
  DEF_x__h12139 = DEF_a__h12092 ^ DEF_b__h12093;
  DEF_x__h12961 = DEF_a__h12859 & DEF_b__h12860;
  DEF_y__h12962 = DEF_x__h12906 & DEF_cin__h12861;
  DEF_x__h12785 = DEF_a__h12663 & DEF_b__h12664;
  DEF_y__h12786 = DEF_x__h12710 & DEF_cin__h12665;
  DEF_x__h12589 = DEF_a__h12466 & DEF_b__h12467;
  DEF_y__h12590 = DEF_x__h12513 & DEF_cin__h12468;
  DEF_x__h12392 = DEF_a__h12269 & DEF_b__h12270;
  DEF_y__h12393 = DEF_x__h12316 & DEF_cin__h12271;
  DEF_x__h12195 = DEF_a__h12092 & DEF_b__h12093;
  DEF_y__h12196 = DEF_x__h12139 & DEF_cin__h12094;
  DEF_x__h12820 = (tUInt8)3u & (((DEF_x__h12961 | DEF_y__h12962) << 1u) | (DEF_x__h12906 ^ DEF_cin__h12861));
  DEF_x__h12624 = (tUInt8)3u & (((DEF_x__h12785 | DEF_y__h12786) << 1u) | (DEF_x__h12710 ^ DEF_cin__h12665));
  DEF_x__h12427 = (tUInt8)3u & (((DEF_x__h12589 | DEF_y__h12590) << 1u) | (DEF_x__h12513 ^ DEF_cin__h12468));
  DEF_x__h12230 = (tUInt8)3u & (((DEF_x__h12392 | DEF_y__h12393) << 1u) | (DEF_x__h12316 ^ DEF_cin__h12271));
  DEF_x__h12053 = (tUInt8)3u & (((DEF_x__h12195 | DEF_y__h12196) << 1u) | (DEF_x__h12139 ^ DEF_cin__h12094));
  DEF_x__h11902 = (tUInt8)3u & (((DEF_a__h11942 & DEF_b__h11943) << 1u) | (DEF_a__h11942 ^ DEF_b__h11943));
  INST_obj_mac_s31.METH_write(DEF_x__h11902);
  INST_obj_mac_s32.METH_write(DEF_x__h12053);
  INST_obj_mac_s33.METH_write(DEF_x__h12230);
  INST_obj_mac_s34.METH_write(DEF_x__h12427);
  INST_obj_mac_s35.METH_write(DEF_x__h12624);
  INST_obj_mac_s36.METH_write(DEF_x__h12820);
  INST_obj_mac_pp00_s3.METH_write(DEF_x__h12996);
  INST_obj_mac_pp01_s3.METH_write(DEF_x__h13029);
  INST_obj_mac_pp10_s3.METH_write(DEF_x__h13062);
  INST_obj_mac_pp77_s3.METH_write(DEF_x__h13095);
  INST_obj_mac_s11_s3.METH_write(DEF_x__h13128);
  INST_obj_mac_s16_s3.METH_write(DEF_x__h13161);
  INST_obj_mac_s21_s3.METH_write(DEF_x__h13193);
  INST_obj_mac_s23_s3.METH_write(DEF_x__h13248);
  INST_obj_mac_s22_s3.METH_write(DEF_x__h13225);
}

void MOD_mk_Test::RL_obj_mac_stage4()
{
  tUInt8 DEF_x__h13268;
  tUInt8 DEF_sum__h14161;
  tUInt8 DEF_x__h14131;
  tUInt8 DEF_sum__h15137;
  tUInt8 DEF_x__h15107;
  tUInt8 DEF_x__h16127;
  tUInt8 DEF_x__h13433;
  tUInt8 DEF_y__h13957;
  tUInt8 DEF_x__h13497;
  tUInt8 DEF_y__h13314;
  tUInt8 DEF_y__h13498;
  tUInt8 DEF_x__h13815;
  tUInt8 DEF_y__h13749;
  tUInt8 DEF_x__h14383;
  tUInt8 DEF_x__h14447;
  tUInt8 DEF_x__h14533;
  tUInt8 DEF_x__h14787;
  tUInt8 DEF_x__h14851;
  tUInt8 DEF_x__h14993;
  tUInt8 DEF_x__h15403;
  tUInt8 DEF_x__h15467;
  tUInt8 DEF_x__h15553;
  tUInt8 DEF_x__h15807;
  tUInt8 DEF_x__h15871;
  tUInt8 DEF_x__h16013;
  tUInt8 DEF_x__h16782;
  tUInt8 DEF_y__h14181;
  tUInt8 DEF_x__h14180;
  tUInt8 DEF_y__h14723;
  tUInt8 DEF_y__h14339;
  tUInt8 DEF_y__h14179;
  tUInt8 DEF_x__h14178;
  tUInt8 DEF_y__h14929;
  tUInt8 DEF_y__h14177;
  tUInt8 DEF_x__h14176;
  tUInt8 DEF_y__h15047;
  tUInt8 DEF_y__h14175;
  tUInt8 DEF_x__h14174;
  tUInt8 DEF_cout__h14160;
  tUInt8 DEF_y__h14721;
  tUInt8 DEF_x__h14720;
  tUInt8 DEF_y__h14719;
  tUInt8 DEF_x__h14718;
  tUInt8 DEF_y__h14927;
  tUInt8 DEF_x__h14926;
  tUInt8 DEF_y__h15157;
  tUInt8 DEF_x__h15156;
  tUInt8 DEF_y__h15743;
  tUInt8 DEF_y__h15359;
  tUInt8 DEF_y__h15155;
  tUInt8 DEF_x__h15154;
  tUInt8 DEF_y__h15949;
  tUInt8 DEF_y__h15404;
  tUInt8 DEF_y__h15153;
  tUInt8 DEF_x__h15152;
  tUInt8 DEF_y__h16067;
  tUInt8 DEF_y__h15468;
  tUInt8 DEF_y__h15151;
  tUInt8 DEF_x__h15150;
  tUInt8 DEF_cout__h15136;
  tUInt8 DEF_y__h15741;
  tUInt8 DEF_x__h15740;
  tUInt8 DEF_y__h15739;
  tUInt8 DEF_x__h15738;
  tUInt8 DEF_y__h15947;
  tUInt8 DEF_x__h15946;
  tUInt8 DEF_y__h16652;
  tUInt8 DEF_x__h16651;
  tUInt8 DEF_y__h16978;
  tUInt8 DEF_y__h16379;
  tUInt8 DEF_y__h16858;
  tUInt8 DEF_x__h16649;
  tUInt8 DEF_obj_mac_pp77_s3_33_AND_obj_mac_s16_s3_34_BIT_4_ETC___d649;
  tUInt8 DEF_x__h14338;
  tUInt8 DEF_y__h14386;
  tUInt8 DEF_x__h15358;
  tUInt8 DEF_y__h15406;
  tUInt8 DEF_y__h15470;
  tUInt8 DEF_y__h15555;
  tUInt8 DEF_x__h16718;
  tUInt8 DEF_y__h16466;
  tUInt8 DEF_y__h13671;
  tUInt8 DEF_p__h13296;
  tUInt8 DEF_sum__h13298;
  tUInt8 DEF_y__h16574;
  tUInt8 DEF_p__h16155;
  tUInt8 DEF_sum__h16157;
  tUInt8 DEF_obj_mac_s32_BIT_0___h14225;
  tUInt8 DEF_obj_mac_s32_BIT_1___h15353;
  tUInt8 DEF_obj_mac_s31_BIT_0___h14247;
  tUInt8 DEF_obj_mac_s31_BIT_1___h14290;
  tUInt8 DEF_y__h14448;
  tUInt8 DEF_obj_mac_s21_s3_03_BITS_3_TO_2_38_AND_obj_mac_s_ETC___d541;
  tUInt8 DEF_y__h14384;
  tUInt8 DEF_y__h14535;
  tUInt8 DEF_obj_mac_s21_s3_03_BITS_3_TO_2_38_XOR_obj_mac_s_ETC___d545;
  tUInt8 DEF_y__h14450;
  tUInt8 DEF_obj_mac_s36_BIT_0___h15201;
  tUInt8 DEF_obj_mac_s36_BIT_1___h16266;
  tUInt8 DEF_obj_mac_s35_BIT_0___h15223;
  tUInt8 DEF_obj_mac_s35_BIT_1___h15290;
  tUInt8 DEF_obj_mac_s34_BIT_0___h15245;
  tUInt8 DEF_obj_mac_s34_BIT_1___h15311;
  tUInt8 DEF_obj_mac_s33_BIT_0___h15267;
  tUInt8 DEF_obj_mac_s33_BIT_1___h15332;
  tUInt8 DEF_y__h13436;
  tUInt8 DEF_x__h13435;
  tUInt8 DEF_y__h13500;
  tUInt8 DEF_obj_mac_s23_s3_BIT_0___h14312;
  tUInt8 DEF_obj_mac_s41_53_BIT_4___d554;
  tUInt8 DEF_obj_mac_s42_07_BIT_4___d608;
  tUInt8 DEF_obj_mac_s16_s3_BIT_4___h16245;
  tUInt8 DEF_obj_mac_s16_BIT_3___h16221;
  tUInt8 DEF_obj_mac_s43_46_BIT_4___d647;
  tUInt8 DEF_obj_mac_s21_s3_BITS_1_TO_0___h13362;
  tUInt8 DEF_obj_mac_s21_s3_BITS_3_TO_2___h14268;
  tUInt8 DEF_obj_mac_s22_s3_BITS_1_TO_0___h14334;
  tUInt8 DEF_x__h17027;
  tUInt8 DEF__read__h1556;
  tUInt8 DEF__read__h1589;
  tUInt8 DEF__read__h1622;
  tUInt8 DEF_obj_mac_s31___d526;
  tUInt8 DEF_obj_mac_s32___d524;
  tUInt8 DEF_obj_mac_s33___d593;
  tUInt8 DEF_obj_mac_s34___d585;
  tUInt8 DEF_obj_mac_s35___d580;
  tUInt8 DEF_obj_mac_s36___d578;
  tUInt8 DEF_obj_mac_s21_s3___d503;
  DEF_obj_mac_s43__h16572 = INST_obj_mac_s43.METH_read();
  DEF_obj_mac_s42__h15661 = INST_obj_mac_s42.METH_read();
  DEF_obj_mac_s41__h14641 = INST_obj_mac_s41.METH_read();
  DEF_obj_mac_s21_s3___d503 = INST_obj_mac_s21_s3.METH_read();
  DEF_x__h11869 = INST_obj_mac_s16.METH_read();
  DEF_obj_mac_s36___d578 = INST_obj_mac_s36.METH_read();
  DEF_obj_mac_s35___d580 = INST_obj_mac_s35.METH_read();
  DEF_obj_mac_s34___d585 = INST_obj_mac_s34.METH_read();
  DEF_obj_mac_s33___d593 = INST_obj_mac_s33.METH_read();
  DEF_obj_mac_s32___d524 = INST_obj_mac_s32.METH_read();
  DEF__read__h1622 = INST_obj_mac_pp77_s3.METH_read();
  DEF_obj_mac_s31___d526 = INST_obj_mac_s31.METH_read();
  DEF__read__h1589 = INST_obj_mac_pp10_s3.METH_read();
  DEF__read__h1556 = INST_obj_mac_pp01_s3.METH_read();
  DEF_x__h17027 = INST_obj_mac_pp00_s3.METH_read();
  DEF_obj_mac_s22_s3_BITS_1_TO_0___h14334 = (tUInt8)((tUInt8)3u & INST_obj_mac_s22_s3.METH_read());
  DEF_obj_mac_s21_s3_BITS_3_TO_2___h14268 = (tUInt8)((tUInt8)3u & (DEF_obj_mac_s21_s3___d503 >> 2u));
  DEF_obj_mac_s21_s3_BITS_1_TO_0___h13362 = (tUInt8)((tUInt8)3u & DEF_obj_mac_s21_s3___d503);
  DEF_obj_mac_s43_46_BIT_4___d647 = (tUInt8)(DEF_obj_mac_s43__h16572 >> 4u);
  DEF_obj_mac_s16_BIT_3___h16221 = (tUInt8)((tUInt8)1u & (DEF_x__h11869 >> 3u));
  DEF_obj_mac_s16_s3_BIT_4___h16245 = (tUInt8)(INST_obj_mac_s16_s3.METH_read() >> 4u);
  DEF_obj_mac_s42_07_BIT_4___d608 = (tUInt8)(DEF_obj_mac_s42__h15661 >> 4u);
  DEF_obj_mac_s41_53_BIT_4___d554 = (tUInt8)(DEF_obj_mac_s41__h14641 >> 4u);
  DEF_obj_mac_s23_s3_BIT_0___h14312 = (tUInt8)((tUInt8)1u & INST_obj_mac_s23_s3.METH_read());
  DEF_y__h13500 = (tUInt8)((tUInt8)1u & INST_obj_mac_s11_s3.METH_read());
  DEF_x__h13435 = (tUInt8)((tUInt8)1u & (DEF_obj_mac_s21_s3___d503 >> 1u));
  DEF_y__h13436 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s21_s3___d503);
  DEF_obj_mac_s33_BIT_1___h15332 = (tUInt8)(DEF_obj_mac_s33___d593 >> 1u);
  DEF_obj_mac_s33_BIT_0___h15267 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s33___d593);
  DEF_obj_mac_s34_BIT_1___h15311 = (tUInt8)(DEF_obj_mac_s34___d585 >> 1u);
  DEF_obj_mac_s34_BIT_0___h15245 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s34___d585);
  DEF_obj_mac_s35_BIT_1___h15290 = (tUInt8)(DEF_obj_mac_s35___d580 >> 1u);
  DEF_obj_mac_s35_BIT_0___h15223 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s35___d580);
  DEF_obj_mac_s36_BIT_1___h16266 = (tUInt8)(DEF_obj_mac_s36___d578 >> 1u);
  DEF_obj_mac_s36_BIT_0___h15201 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s36___d578);
  DEF_obj_mac_s21_s3_03_BITS_3_TO_2_38_XOR_obj_mac_s_ETC___d545 = DEF_obj_mac_s21_s3_BITS_3_TO_2___h14268 ^ DEF_obj_mac_s22_s3_BITS_1_TO_0___h14334;
  DEF_y__h14450 = (tUInt8)(DEF_obj_mac_s21_s3_03_BITS_3_TO_2_38_XOR_obj_mac_s_ETC___d545 >> 1u);
  DEF_y__h14535 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s21_s3_03_BITS_3_TO_2_38_XOR_obj_mac_s_ETC___d545);
  DEF_obj_mac_s31_BIT_1___h14290 = (tUInt8)(DEF_obj_mac_s31___d526 >> 1u);
  DEF_obj_mac_s21_s3_03_BITS_3_TO_2_38_AND_obj_mac_s_ETC___d541 = DEF_obj_mac_s21_s3_BITS_3_TO_2___h14268 & DEF_obj_mac_s22_s3_BITS_1_TO_0___h14334;
  DEF_y__h14384 = (tUInt8)(DEF_obj_mac_s21_s3_03_BITS_3_TO_2_38_AND_obj_mac_s_ETC___d541 >> 1u);
  DEF_y__h14448 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s21_s3_03_BITS_3_TO_2_38_AND_obj_mac_s_ETC___d541);
  DEF_obj_mac_s31_BIT_0___h14247 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s31___d526);
  DEF_obj_mac_s32_BIT_1___h15353 = (tUInt8)(DEF_obj_mac_s32___d524 >> 1u);
  DEF_obj_mac_s32_BIT_0___h14225 = (tUInt8)((tUInt8)1u & DEF_obj_mac_s32___d524);
  DEF_p__h13296 = (tUInt8)15u & (((DEF_obj_mac_s21_s3_BITS_1_TO_0___h13362 << 2u) | (DEF_y__h13500 << 1u)) | (DEF__read__h1556 ^ DEF__read__h1589));
  DEF_y__h16466 = DEF_obj_mac_s16_BIT_3___h16221 ^ DEF_obj_mac_s36_BIT_1___h16266;
  DEF_x__h16718 = DEF__read__h1622 ^ DEF_obj_mac_s16_s3_BIT_4___h16245;
  DEF_p__h16155 = (tUInt8)15u & ((((tUInt8)1u << 2u) | (DEF_x__h16718 << 1u)) | DEF_y__h16466);
  DEF_y__h15555 = DEF_obj_mac_s33_BIT_0___h15267 ^ DEF_obj_mac_s32_BIT_1___h15353;
  DEF_y__h15470 = DEF_obj_mac_s34_BIT_0___h15245 ^ DEF_obj_mac_s33_BIT_1___h15332;
  DEF_y__h15406 = DEF_obj_mac_s35_BIT_0___h15223 ^ DEF_obj_mac_s34_BIT_1___h15311;
  DEF_x__h15358 = DEF_obj_mac_s36_BIT_0___h15201 ^ DEF_obj_mac_s35_BIT_1___h15290;
  DEF_y__h14386 = DEF_obj_mac_s31_BIT_0___h14247 ^ DEF_obj_mac_s23_s3_BIT_0___h14312;
  DEF_x__h14338 = DEF_obj_mac_s32_BIT_0___h14225 ^ DEF_obj_mac_s31_BIT_1___h14290;
  DEF_y__h16379 = DEF_obj_mac_s16_BIT_3___h16221 & DEF_obj_mac_s36_BIT_1___h16266;
  DEF_y__h16978 = DEF_y__h16466 & DEF_obj_mac_s43_46_BIT_4___d647;
  DEF_x__h16651 = DEF__read__h1622 & DEF_obj_mac_s16_s3_BIT_4___h16245;
  DEF_y__h16652 = DEF_x__h16718 & DEF_y__h16379;
  DEF_x__h16649 = DEF_x__h16651 | DEF_y__h16652;
  DEF_y__h15468 = DEF_obj_mac_s33_BIT_0___h15267 & DEF_obj_mac_s32_BIT_1___h15353;
  DEF_y__h16067 = DEF_y__h15555 & DEF_obj_mac_s42_07_BIT_4___d608;
  DEF_y__h15404 = DEF_obj_mac_s34_BIT_0___h15245 & DEF_obj_mac_s33_BIT_1___h15332;
  DEF_y__h15949 = DEF_y__h15470 & DEF_y__h15468;
  DEF_x__h15946 = DEF_y__h15404 | DEF_y__h15949;
  DEF_y__h15359 = DEF_obj_mac_s35_BIT_0___h15223 & DEF_obj_mac_s34_BIT_1___h15311;
  DEF_y__h15743 = DEF_y__h15406 & DEF_y__h15404;
  DEF_x__h15740 = DEF_y__h15359 | DEF_y__h15743;
  DEF_x__h15156 = DEF_obj_mac_s36_BIT_0___h15201 & DEF_obj_mac_s35_BIT_1___h15290;
  DEF_y__h15157 = DEF_x__h15358 & DEF_y__h15359;
  DEF_x__h15154 = DEF_x__h15156 | DEF_y__h15157;
  DEF_y__h15047 = DEF_y__h14535 & DEF_obj_mac_s41_53_BIT_4___d554;
  DEF_y__h14929 = DEF_y__h14450 & DEF_y__h14448;
  DEF_x__h14926 = DEF_y__h14384 | DEF_y__h14929;
  DEF_y__h14339 = DEF_obj_mac_s31_BIT_0___h14247 & DEF_obj_mac_s23_s3_BIT_0___h14312;
  DEF_y__h14723 = DEF_y__h14386 & DEF_y__h14384;
  DEF_x__h14720 = DEF_y__h14339 | DEF_y__h14723;
  DEF_x__h14180 = DEF_obj_mac_s32_BIT_0___h14225 & DEF_obj_mac_s31_BIT_1___h14290;
  DEF_y__h14181 = DEF_x__h14338 & DEF_y__h14339;
  DEF_x__h14178 = DEF_x__h14180 | DEF_y__h14181;
  DEF_x__h16782 = DEF_x__h16718 & DEF_y__h16466;
  DEF_y__h16858 = DEF_x__h16782 & DEF_obj_mac_s43_46_BIT_4___d647;
  DEF_obj_mac_pp77_s3_33_AND_obj_mac_s16_s3_34_BIT_4_ETC___d649 = DEF_x__h16649 | DEF_y__h16858;
  DEF_y__h16574 = (tUInt8)15u & ((((DEF_obj_mac_pp77_s3_33_AND_obj_mac_s16_s3_34_BIT_4_ETC___d649 << 3u) | (DEF_obj_mac_pp77_s3_33_AND_obj_mac_s16_s3_34_BIT_4_ETC___d649 << 2u)) | ((DEF_y__h16379 | DEF_y__h16978) << 1u)) | DEF_obj_mac_s43_46_BIT_4___d647);
  DEF_sum__h16157 = DEF_p__h16155 ^ DEF_y__h16574;
  DEF_x__h16013 = DEF_y__h15470 & DEF_y__h15555;
  DEF_y__h15947 = DEF_x__h16013 & DEF_obj_mac_s42_07_BIT_4___d608;
  DEF_x__h15807 = DEF_y__h15406 & DEF_y__h15470;
  DEF_y__h15741 = DEF_x__h15807 & DEF_y__h15468;
  DEF_x__h15738 = DEF_x__h15740 | DEF_y__h15741;
  DEF_x__h15871 = DEF_x__h15807 & DEF_y__h15555;
  DEF_y__h15739 = DEF_x__h15871 & DEF_obj_mac_s42_07_BIT_4___d608;
  DEF_x__h15403 = DEF_x__h15358 & DEF_y__h15406;
  DEF_y__h15155 = DEF_x__h15403 & DEF_y__h15404;
  DEF_x__h15152 = DEF_x__h15154 | DEF_y__h15155;
  DEF_x__h15467 = DEF_x__h15403 & DEF_y__h15470;
  DEF_y__h15153 = DEF_x__h15467 & DEF_y__h15468;
  DEF_x__h15150 = DEF_x__h15152 | DEF_y__h15153;
  DEF_x__h15553 = DEF_x__h15467 & DEF_y__h15555;
  DEF_y__h15151 = DEF_x__h15553 & DEF_obj_mac_s42_07_BIT_4___d608;
  DEF_cout__h15136 = DEF_x__h15150 | DEF_y__h15151;
  DEF_x__h14993 = DEF_y__h14450 & DEF_y__h14535;
  DEF_y__h14927 = DEF_x__h14993 & DEF_obj_mac_s41_53_BIT_4___d554;
  DEF_x__h14787 = DEF_y__h14386 & DEF_y__h14450;
  DEF_y__h14721 = DEF_x__h14787 & DEF_y__h14448;
  DEF_x__h14718 = DEF_x__h14720 | DEF_y__h14721;
  DEF_x__h14851 = DEF_x__h14787 & DEF_y__h14535;
  DEF_y__h14719 = DEF_x__h14851 & DEF_obj_mac_s41_53_BIT_4___d554;
  DEF_x__h14383 = DEF_x__h14338 & DEF_y__h14386;
  DEF_y__h14179 = DEF_x__h14383 & DEF_y__h14384;
  DEF_x__h14176 = DEF_x__h14178 | DEF_y__h14179;
  DEF_x__h14447 = DEF_x__h14383 & DEF_y__h14450;
  DEF_y__h14177 = DEF_x__h14447 & DEF_y__h14448;
  DEF_x__h14174 = DEF_x__h14176 | DEF_y__h14177;
  DEF_x__h14533 = DEF_x__h14447 & DEF_y__h14535;
  DEF_y__h14175 = DEF_x__h14533 & DEF_obj_mac_s41_53_BIT_4___d554;
  DEF_cout__h14160 = DEF_x__h14174 | DEF_y__h14175;
  DEF_x__h13815 = DEF_y__h13436 & DEF_y__h13500;
  DEF_y__h13498 = DEF__read__h1556 & DEF__read__h1589;
  DEF_y__h13749 = DEF_x__h13815 & DEF_y__h13498;
  DEF_y__h13957 = DEF_y__h13500 & DEF_y__h13498;
  DEF_y__h13671 = (tUInt8)15u & (((DEF_y__h13749 << 3u) | (DEF_y__h13957 << 2u)) | (DEF_y__h13498 << 1u));
  DEF_sum__h13298 = DEF_p__h13296 ^ DEF_y__h13671;
  DEF_x__h13433 = DEF_x__h13435 & DEF_y__h13436;
  DEF_x__h13497 = DEF_x__h13433 & DEF_y__h13500;
  DEF_y__h13314 = DEF_x__h13497 & DEF_y__h13498;
  DEF_x__h16127 = (tUInt8)31u & DEF_sum__h16157;
  DEF_sum__h15137 = (tUInt8)15u & (((((DEF_x__h15358 ^ (DEF_x__h15738 | DEF_y__h15739)) << 3u) | ((DEF_y__h15406 ^ (DEF_x__h15946 | DEF_y__h15947)) << 2u)) | ((DEF_y__h15470 ^ (DEF_y__h15468 | DEF_y__h16067)) << 1u)) | (DEF_y__h15555 ^ DEF_obj_mac_s42_07_BIT_4___d608));
  DEF_x__h15107 = (tUInt8)31u & ((DEF_cout__h15136 << 4u) | DEF_sum__h15137);
  DEF_sum__h14161 = (tUInt8)15u & ((((DEF_x__h14338 ^ (DEF_x__h14718 | DEF_y__h14719)) << 3u) | ((DEF_y__h14386 ^ (DEF_x__h14926 | DEF_y__h14927)) << 2u)) | (DEF_obj_mac_s21_s3_03_BITS_3_TO_2_38_XOR_obj_mac_s_ETC___d545 ^ ((tUInt8)3u & (((DEF_y__h14448 | DEF_y__h15047) << 1u) | DEF_obj_mac_s41_53_BIT_4___d554))));
  DEF_x__h14131 = (tUInt8)31u & ((DEF_cout__h14160 << 4u) | DEF_sum__h14161);
  DEF_x__h13268 = (tUInt8)31u & ((DEF_y__h13314 << 4u) | DEF_sum__h13298);
  INST_obj_mac_s41.METH_write(DEF_x__h13268);
  INST_obj_mac_s42.METH_write(DEF_x__h14131);
  INST_obj_mac_s43.METH_write(DEF_x__h15107);
  INST_obj_mac_s44.METH_write(DEF_x__h16127);
  INST_obj_mac_pp00_s4.METH_write(DEF_x__h17027);
}

void MOD_mk_Test::RL_obj_mac_res1()
{
  tUInt32 DEF_z_out__h17036;
  tUInt8 DEF__read__h1952;
  DEF_obj_mac_s43__h16572 = INST_obj_mac_s43.METH_read();
  DEF_obj_mac_s42__h15661 = INST_obj_mac_s42.METH_read();
  DEF_obj_mac_s41__h14641 = INST_obj_mac_s41.METH_read();
  DEF__read__h1952 = INST_obj_mac_pp00_s4.METH_read();
  DEF_z_out__h17036 = 65535u & (((((((tUInt32)((tUInt8)((tUInt8)7u & INST_obj_mac_s44.METH_read()))) << 13u) | (((tUInt32)((tUInt8)((tUInt8)15u & DEF_obj_mac_s43__h16572))) << 9u)) | (((tUInt32)((tUInt8)((tUInt8)15u & DEF_obj_mac_s42__h15661))) << 5u)) | (((tUInt32)((tUInt8)((tUInt8)15u & DEF_obj_mac_s41__h14641))) << 1u)) | (tUInt32)(DEF__read__h1952));
  INST_obj_mac_z.METH_write(DEF_z_out__h17036);
}

void MOD_mk_Test::RL_inp()
{
  tUInt8 DEF_a__h17412;
  tUInt8 DEF_b__h17413;
  DEF_b__h17397 = INST_count.METH_read();
  DEF_b__h17413 = INST_rg_b.METH_read();
  DEF_a__h17412 = INST_rg_a.METH_read();
  DEF_count_65_PLUS_1___d669 = DEF_b__h17397 + 1u;
  INST_obj_mac_x.METH_write(DEF_a__h17412);
  INST_obj_mac_y.METH_write(DEF_b__h17413);
  INST_count.METH_write(DEF_count_65_PLUS_1___d669);
}

void MOD_mk_Test::RL_stall()
{
  DEF_b__h17397 = INST_count.METH_read();
  DEF_count_65_PLUS_1___d669 = DEF_b__h17397 + 1u;
  INST_count.METH_write(DEF_count_65_PLUS_1___d669);
}

void MOD_mk_Test::RL_res()
{
  tUInt32 DEF_signed_obj_mac_z_75___d676;
  tUInt32 DEF_signed_count_65___d674;
  DEF_b__h17397 = INST_count.METH_read();
  DEF_signed_count_65___d674 = DEF_b__h17397;
  DEF_signed_obj_mac_z_75___d676 = INST_obj_mac_z.METH_read();
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,-32,-16",
		   &__str_literal_1,
		   DEF_signed_count_65___d674,
		   DEF_signed_obj_mac_z_75___d676);
}

void MOD_mk_Test::RL_stop()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_finish(sim_hdl, "32", 0u);
}


/* Methods */


/* Reset routines */

void MOD_mk_Test::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_rg_c.reset_RST(ARG_rst_in);
  INST_rg_b.reset_RST(ARG_rst_in);
  INST_rg_a.reset_RST(ARG_rst_in);
  INST_obj_mac_z.reset_RST(ARG_rst_in);
  INST_obj_mac_y.reset_RST(ARG_rst_in);
  INST_obj_mac_x.reset_RST(ARG_rst_in);
  INST_obj_mac_s44.reset_RST(ARG_rst_in);
  INST_obj_mac_s43.reset_RST(ARG_rst_in);
  INST_obj_mac_s42.reset_RST(ARG_rst_in);
  INST_obj_mac_s41.reset_RST(ARG_rst_in);
  INST_obj_mac_s36.reset_RST(ARG_rst_in);
  INST_obj_mac_s35.reset_RST(ARG_rst_in);
  INST_obj_mac_s34.reset_RST(ARG_rst_in);
  INST_obj_mac_s33.reset_RST(ARG_rst_in);
  INST_obj_mac_s32.reset_RST(ARG_rst_in);
  INST_obj_mac_s31.reset_RST(ARG_rst_in);
  INST_obj_mac_s23_s3.reset_RST(ARG_rst_in);
  INST_obj_mac_s23.reset_RST(ARG_rst_in);
  INST_obj_mac_s22_s3.reset_RST(ARG_rst_in);
  INST_obj_mac_s22.reset_RST(ARG_rst_in);
  INST_obj_mac_s21_s3.reset_RST(ARG_rst_in);
  INST_obj_mac_s21.reset_RST(ARG_rst_in);
  INST_obj_mac_s16_s3.reset_RST(ARG_rst_in);
  INST_obj_mac_s16_s2.reset_RST(ARG_rst_in);
  INST_obj_mac_s16.reset_RST(ARG_rst_in);
  INST_obj_mac_s15_s2.reset_RST(ARG_rst_in);
  INST_obj_mac_s15.reset_RST(ARG_rst_in);
  INST_obj_mac_s14.reset_RST(ARG_rst_in);
  INST_obj_mac_s13.reset_RST(ARG_rst_in);
  INST_obj_mac_s12.reset_RST(ARG_rst_in);
  INST_obj_mac_s11_s3.reset_RST(ARG_rst_in);
  INST_obj_mac_s11_s2.reset_RST(ARG_rst_in);
  INST_obj_mac_s11.reset_RST(ARG_rst_in);
  INST_obj_mac_pp77_s3.reset_RST(ARG_rst_in);
  INST_obj_mac_pp77_s2.reset_RST(ARG_rst_in);
  INST_obj_mac_pp77.reset_RST(ARG_rst_in);
  INST_obj_mac_pp57_s2.reset_RST(ARG_rst_in);
  INST_obj_mac_pp57.reset_RST(ARG_rst_in);
  INST_obj_mac_pp50.reset_RST(ARG_rst_in);
  INST_obj_mac_pp41.reset_RST(ARG_rst_in);
  INST_obj_mac_pp35_s2.reset_RST(ARG_rst_in);
  INST_obj_mac_pp35.reset_RST(ARG_rst_in);
  INST_obj_mac_pp30.reset_RST(ARG_rst_in);
  INST_obj_mac_pp21.reset_RST(ARG_rst_in);
  INST_obj_mac_pp16.reset_RST(ARG_rst_in);
  INST_obj_mac_pp10_s3.reset_RST(ARG_rst_in);
  INST_obj_mac_pp10_s2.reset_RST(ARG_rst_in);
  INST_obj_mac_pp10.reset_RST(ARG_rst_in);
  INST_obj_mac_pp07.reset_RST(ARG_rst_in);
  INST_obj_mac_pp01_s3.reset_RST(ARG_rst_in);
  INST_obj_mac_pp01_s2.reset_RST(ARG_rst_in);
  INST_obj_mac_pp01.reset_RST(ARG_rst_in);
  INST_obj_mac_pp00_s4.reset_RST(ARG_rst_in);
  INST_obj_mac_pp00_s3.reset_RST(ARG_rst_in);
  INST_obj_mac_pp00_s2.reset_RST(ARG_rst_in);
  INST_obj_mac_pp00.reset_RST(ARG_rst_in);
  INST_count.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mk_Test::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mk_Test::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_count.dump_state(indent + 2u);
  INST_obj_mac_pp00.dump_state(indent + 2u);
  INST_obj_mac_pp00_s2.dump_state(indent + 2u);
  INST_obj_mac_pp00_s3.dump_state(indent + 2u);
  INST_obj_mac_pp00_s4.dump_state(indent + 2u);
  INST_obj_mac_pp01.dump_state(indent + 2u);
  INST_obj_mac_pp01_s2.dump_state(indent + 2u);
  INST_obj_mac_pp01_s3.dump_state(indent + 2u);
  INST_obj_mac_pp07.dump_state(indent + 2u);
  INST_obj_mac_pp10.dump_state(indent + 2u);
  INST_obj_mac_pp10_s2.dump_state(indent + 2u);
  INST_obj_mac_pp10_s3.dump_state(indent + 2u);
  INST_obj_mac_pp16.dump_state(indent + 2u);
  INST_obj_mac_pp21.dump_state(indent + 2u);
  INST_obj_mac_pp30.dump_state(indent + 2u);
  INST_obj_mac_pp35.dump_state(indent + 2u);
  INST_obj_mac_pp35_s2.dump_state(indent + 2u);
  INST_obj_mac_pp41.dump_state(indent + 2u);
  INST_obj_mac_pp50.dump_state(indent + 2u);
  INST_obj_mac_pp57.dump_state(indent + 2u);
  INST_obj_mac_pp57_s2.dump_state(indent + 2u);
  INST_obj_mac_pp77.dump_state(indent + 2u);
  INST_obj_mac_pp77_s2.dump_state(indent + 2u);
  INST_obj_mac_pp77_s3.dump_state(indent + 2u);
  INST_obj_mac_s11.dump_state(indent + 2u);
  INST_obj_mac_s11_s2.dump_state(indent + 2u);
  INST_obj_mac_s11_s3.dump_state(indent + 2u);
  INST_obj_mac_s12.dump_state(indent + 2u);
  INST_obj_mac_s13.dump_state(indent + 2u);
  INST_obj_mac_s14.dump_state(indent + 2u);
  INST_obj_mac_s15.dump_state(indent + 2u);
  INST_obj_mac_s15_s2.dump_state(indent + 2u);
  INST_obj_mac_s16.dump_state(indent + 2u);
  INST_obj_mac_s16_s2.dump_state(indent + 2u);
  INST_obj_mac_s16_s3.dump_state(indent + 2u);
  INST_obj_mac_s21.dump_state(indent + 2u);
  INST_obj_mac_s21_s3.dump_state(indent + 2u);
  INST_obj_mac_s22.dump_state(indent + 2u);
  INST_obj_mac_s22_s3.dump_state(indent + 2u);
  INST_obj_mac_s23.dump_state(indent + 2u);
  INST_obj_mac_s23_s3.dump_state(indent + 2u);
  INST_obj_mac_s31.dump_state(indent + 2u);
  INST_obj_mac_s32.dump_state(indent + 2u);
  INST_obj_mac_s33.dump_state(indent + 2u);
  INST_obj_mac_s34.dump_state(indent + 2u);
  INST_obj_mac_s35.dump_state(indent + 2u);
  INST_obj_mac_s36.dump_state(indent + 2u);
  INST_obj_mac_s41.dump_state(indent + 2u);
  INST_obj_mac_s42.dump_state(indent + 2u);
  INST_obj_mac_s43.dump_state(indent + 2u);
  INST_obj_mac_s44.dump_state(indent + 2u);
  INST_obj_mac_x.dump_state(indent + 2u);
  INST_obj_mac_y.dump_state(indent + 2u);
  INST_obj_mac_z.dump_state(indent + 2u);
  INST_rg_a.dump_state(indent + 2u);
  INST_rg_b.dump_state(indent + 2u);
  INST_rg_c.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mk_Test::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 82u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_inp", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_obj_mac_res1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_obj_mac_stage1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_obj_mac_stage2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_obj_mac_stage3", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_obj_mac_stage4", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_res", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_stall", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_stop", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_inp", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_obj_mac_res1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_obj_mac_stage1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_obj_mac_stage2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_obj_mac_stage3", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_obj_mac_stage4", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_res", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_stall", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_stop", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h17397", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "count_65_PLUS_1___d669", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "obj_mac_s41__h14641", 5u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "obj_mac_s42__h15661", 5u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "obj_mac_s43__h16572", 5u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h11869", 5u);
  num = INST_count.dump_VCD_defs(num);
  num = INST_obj_mac_pp00.dump_VCD_defs(num);
  num = INST_obj_mac_pp00_s2.dump_VCD_defs(num);
  num = INST_obj_mac_pp00_s3.dump_VCD_defs(num);
  num = INST_obj_mac_pp00_s4.dump_VCD_defs(num);
  num = INST_obj_mac_pp01.dump_VCD_defs(num);
  num = INST_obj_mac_pp01_s2.dump_VCD_defs(num);
  num = INST_obj_mac_pp01_s3.dump_VCD_defs(num);
  num = INST_obj_mac_pp07.dump_VCD_defs(num);
  num = INST_obj_mac_pp10.dump_VCD_defs(num);
  num = INST_obj_mac_pp10_s2.dump_VCD_defs(num);
  num = INST_obj_mac_pp10_s3.dump_VCD_defs(num);
  num = INST_obj_mac_pp16.dump_VCD_defs(num);
  num = INST_obj_mac_pp21.dump_VCD_defs(num);
  num = INST_obj_mac_pp30.dump_VCD_defs(num);
  num = INST_obj_mac_pp35.dump_VCD_defs(num);
  num = INST_obj_mac_pp35_s2.dump_VCD_defs(num);
  num = INST_obj_mac_pp41.dump_VCD_defs(num);
  num = INST_obj_mac_pp50.dump_VCD_defs(num);
  num = INST_obj_mac_pp57.dump_VCD_defs(num);
  num = INST_obj_mac_pp57_s2.dump_VCD_defs(num);
  num = INST_obj_mac_pp77.dump_VCD_defs(num);
  num = INST_obj_mac_pp77_s2.dump_VCD_defs(num);
  num = INST_obj_mac_pp77_s3.dump_VCD_defs(num);
  num = INST_obj_mac_s11.dump_VCD_defs(num);
  num = INST_obj_mac_s11_s2.dump_VCD_defs(num);
  num = INST_obj_mac_s11_s3.dump_VCD_defs(num);
  num = INST_obj_mac_s12.dump_VCD_defs(num);
  num = INST_obj_mac_s13.dump_VCD_defs(num);
  num = INST_obj_mac_s14.dump_VCD_defs(num);
  num = INST_obj_mac_s15.dump_VCD_defs(num);
  num = INST_obj_mac_s15_s2.dump_VCD_defs(num);
  num = INST_obj_mac_s16.dump_VCD_defs(num);
  num = INST_obj_mac_s16_s2.dump_VCD_defs(num);
  num = INST_obj_mac_s16_s3.dump_VCD_defs(num);
  num = INST_obj_mac_s21.dump_VCD_defs(num);
  num = INST_obj_mac_s21_s3.dump_VCD_defs(num);
  num = INST_obj_mac_s22.dump_VCD_defs(num);
  num = INST_obj_mac_s22_s3.dump_VCD_defs(num);
  num = INST_obj_mac_s23.dump_VCD_defs(num);
  num = INST_obj_mac_s23_s3.dump_VCD_defs(num);
  num = INST_obj_mac_s31.dump_VCD_defs(num);
  num = INST_obj_mac_s32.dump_VCD_defs(num);
  num = INST_obj_mac_s33.dump_VCD_defs(num);
  num = INST_obj_mac_s34.dump_VCD_defs(num);
  num = INST_obj_mac_s35.dump_VCD_defs(num);
  num = INST_obj_mac_s36.dump_VCD_defs(num);
  num = INST_obj_mac_s41.dump_VCD_defs(num);
  num = INST_obj_mac_s42.dump_VCD_defs(num);
  num = INST_obj_mac_s43.dump_VCD_defs(num);
  num = INST_obj_mac_s44.dump_VCD_defs(num);
  num = INST_obj_mac_x.dump_VCD_defs(num);
  num = INST_obj_mac_y.dump_VCD_defs(num);
  num = INST_obj_mac_z.dump_VCD_defs(num);
  num = INST_rg_a.dump_VCD_defs(num);
  num = INST_rg_b.dump_VCD_defs(num);
  num = INST_rg_c.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mk_Test::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mk_Test &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mk_Test::vcd_defs(tVCDDumpType dt, MOD_mk_Test &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 5u);
    vcd_write_x(sim_hdl, num++, 5u);
    vcd_write_x(sim_hdl, num++, 5u);
    vcd_write_x(sim_hdl, num++, 5u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_inp) != DEF_CAN_FIRE_RL_inp)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_inp, 1u);
	backing.DEF_CAN_FIRE_RL_inp = DEF_CAN_FIRE_RL_inp;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_obj_mac_res1) != DEF_CAN_FIRE_RL_obj_mac_res1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_obj_mac_res1, 1u);
	backing.DEF_CAN_FIRE_RL_obj_mac_res1 = DEF_CAN_FIRE_RL_obj_mac_res1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_obj_mac_stage1) != DEF_CAN_FIRE_RL_obj_mac_stage1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_obj_mac_stage1, 1u);
	backing.DEF_CAN_FIRE_RL_obj_mac_stage1 = DEF_CAN_FIRE_RL_obj_mac_stage1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_obj_mac_stage2) != DEF_CAN_FIRE_RL_obj_mac_stage2)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_obj_mac_stage2, 1u);
	backing.DEF_CAN_FIRE_RL_obj_mac_stage2 = DEF_CAN_FIRE_RL_obj_mac_stage2;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_obj_mac_stage3) != DEF_CAN_FIRE_RL_obj_mac_stage3)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_obj_mac_stage3, 1u);
	backing.DEF_CAN_FIRE_RL_obj_mac_stage3 = DEF_CAN_FIRE_RL_obj_mac_stage3;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_obj_mac_stage4) != DEF_CAN_FIRE_RL_obj_mac_stage4)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_obj_mac_stage4, 1u);
	backing.DEF_CAN_FIRE_RL_obj_mac_stage4 = DEF_CAN_FIRE_RL_obj_mac_stage4;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_res) != DEF_CAN_FIRE_RL_res)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_res, 1u);
	backing.DEF_CAN_FIRE_RL_res = DEF_CAN_FIRE_RL_res;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_stall) != DEF_CAN_FIRE_RL_stall)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_stall, 1u);
	backing.DEF_CAN_FIRE_RL_stall = DEF_CAN_FIRE_RL_stall;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_stop) != DEF_CAN_FIRE_RL_stop)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_stop, 1u);
	backing.DEF_CAN_FIRE_RL_stop = DEF_CAN_FIRE_RL_stop;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_inp) != DEF_WILL_FIRE_RL_inp)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_inp, 1u);
	backing.DEF_WILL_FIRE_RL_inp = DEF_WILL_FIRE_RL_inp;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_obj_mac_res1) != DEF_WILL_FIRE_RL_obj_mac_res1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_obj_mac_res1, 1u);
	backing.DEF_WILL_FIRE_RL_obj_mac_res1 = DEF_WILL_FIRE_RL_obj_mac_res1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_obj_mac_stage1) != DEF_WILL_FIRE_RL_obj_mac_stage1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_obj_mac_stage1, 1u);
	backing.DEF_WILL_FIRE_RL_obj_mac_stage1 = DEF_WILL_FIRE_RL_obj_mac_stage1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_obj_mac_stage2) != DEF_WILL_FIRE_RL_obj_mac_stage2)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_obj_mac_stage2, 1u);
	backing.DEF_WILL_FIRE_RL_obj_mac_stage2 = DEF_WILL_FIRE_RL_obj_mac_stage2;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_obj_mac_stage3) != DEF_WILL_FIRE_RL_obj_mac_stage3)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_obj_mac_stage3, 1u);
	backing.DEF_WILL_FIRE_RL_obj_mac_stage3 = DEF_WILL_FIRE_RL_obj_mac_stage3;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_obj_mac_stage4) != DEF_WILL_FIRE_RL_obj_mac_stage4)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_obj_mac_stage4, 1u);
	backing.DEF_WILL_FIRE_RL_obj_mac_stage4 = DEF_WILL_FIRE_RL_obj_mac_stage4;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_res) != DEF_WILL_FIRE_RL_res)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_res, 1u);
	backing.DEF_WILL_FIRE_RL_res = DEF_WILL_FIRE_RL_res;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_stall) != DEF_WILL_FIRE_RL_stall)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_stall, 1u);
	backing.DEF_WILL_FIRE_RL_stall = DEF_WILL_FIRE_RL_stall;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_stop) != DEF_WILL_FIRE_RL_stop)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_stop, 1u);
	backing.DEF_WILL_FIRE_RL_stop = DEF_WILL_FIRE_RL_stop;
      }
      ++num;
      if ((backing.DEF_b__h17397) != DEF_b__h17397)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h17397, 32u);
	backing.DEF_b__h17397 = DEF_b__h17397;
      }
      ++num;
      if ((backing.DEF_count_65_PLUS_1___d669) != DEF_count_65_PLUS_1___d669)
      {
	vcd_write_val(sim_hdl, num, DEF_count_65_PLUS_1___d669, 32u);
	backing.DEF_count_65_PLUS_1___d669 = DEF_count_65_PLUS_1___d669;
      }
      ++num;
      if ((backing.DEF_obj_mac_s41__h14641) != DEF_obj_mac_s41__h14641)
      {
	vcd_write_val(sim_hdl, num, DEF_obj_mac_s41__h14641, 5u);
	backing.DEF_obj_mac_s41__h14641 = DEF_obj_mac_s41__h14641;
      }
      ++num;
      if ((backing.DEF_obj_mac_s42__h15661) != DEF_obj_mac_s42__h15661)
      {
	vcd_write_val(sim_hdl, num, DEF_obj_mac_s42__h15661, 5u);
	backing.DEF_obj_mac_s42__h15661 = DEF_obj_mac_s42__h15661;
      }
      ++num;
      if ((backing.DEF_obj_mac_s43__h16572) != DEF_obj_mac_s43__h16572)
      {
	vcd_write_val(sim_hdl, num, DEF_obj_mac_s43__h16572, 5u);
	backing.DEF_obj_mac_s43__h16572 = DEF_obj_mac_s43__h16572;
      }
      ++num;
      if ((backing.DEF_x__h11869) != DEF_x__h11869)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h11869, 5u);
	backing.DEF_x__h11869 = DEF_x__h11869;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_inp, 1u);
      backing.DEF_CAN_FIRE_RL_inp = DEF_CAN_FIRE_RL_inp;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_obj_mac_res1, 1u);
      backing.DEF_CAN_FIRE_RL_obj_mac_res1 = DEF_CAN_FIRE_RL_obj_mac_res1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_obj_mac_stage1, 1u);
      backing.DEF_CAN_FIRE_RL_obj_mac_stage1 = DEF_CAN_FIRE_RL_obj_mac_stage1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_obj_mac_stage2, 1u);
      backing.DEF_CAN_FIRE_RL_obj_mac_stage2 = DEF_CAN_FIRE_RL_obj_mac_stage2;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_obj_mac_stage3, 1u);
      backing.DEF_CAN_FIRE_RL_obj_mac_stage3 = DEF_CAN_FIRE_RL_obj_mac_stage3;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_obj_mac_stage4, 1u);
      backing.DEF_CAN_FIRE_RL_obj_mac_stage4 = DEF_CAN_FIRE_RL_obj_mac_stage4;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_res, 1u);
      backing.DEF_CAN_FIRE_RL_res = DEF_CAN_FIRE_RL_res;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_stall, 1u);
      backing.DEF_CAN_FIRE_RL_stall = DEF_CAN_FIRE_RL_stall;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_stop, 1u);
      backing.DEF_CAN_FIRE_RL_stop = DEF_CAN_FIRE_RL_stop;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_inp, 1u);
      backing.DEF_WILL_FIRE_RL_inp = DEF_WILL_FIRE_RL_inp;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_obj_mac_res1, 1u);
      backing.DEF_WILL_FIRE_RL_obj_mac_res1 = DEF_WILL_FIRE_RL_obj_mac_res1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_obj_mac_stage1, 1u);
      backing.DEF_WILL_FIRE_RL_obj_mac_stage1 = DEF_WILL_FIRE_RL_obj_mac_stage1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_obj_mac_stage2, 1u);
      backing.DEF_WILL_FIRE_RL_obj_mac_stage2 = DEF_WILL_FIRE_RL_obj_mac_stage2;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_obj_mac_stage3, 1u);
      backing.DEF_WILL_FIRE_RL_obj_mac_stage3 = DEF_WILL_FIRE_RL_obj_mac_stage3;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_obj_mac_stage4, 1u);
      backing.DEF_WILL_FIRE_RL_obj_mac_stage4 = DEF_WILL_FIRE_RL_obj_mac_stage4;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_res, 1u);
      backing.DEF_WILL_FIRE_RL_res = DEF_WILL_FIRE_RL_res;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_stall, 1u);
      backing.DEF_WILL_FIRE_RL_stall = DEF_WILL_FIRE_RL_stall;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_stop, 1u);
      backing.DEF_WILL_FIRE_RL_stop = DEF_WILL_FIRE_RL_stop;
      vcd_write_val(sim_hdl, num++, DEF_b__h17397, 32u);
      backing.DEF_b__h17397 = DEF_b__h17397;
      vcd_write_val(sim_hdl, num++, DEF_count_65_PLUS_1___d669, 32u);
      backing.DEF_count_65_PLUS_1___d669 = DEF_count_65_PLUS_1___d669;
      vcd_write_val(sim_hdl, num++, DEF_obj_mac_s41__h14641, 5u);
      backing.DEF_obj_mac_s41__h14641 = DEF_obj_mac_s41__h14641;
      vcd_write_val(sim_hdl, num++, DEF_obj_mac_s42__h15661, 5u);
      backing.DEF_obj_mac_s42__h15661 = DEF_obj_mac_s42__h15661;
      vcd_write_val(sim_hdl, num++, DEF_obj_mac_s43__h16572, 5u);
      backing.DEF_obj_mac_s43__h16572 = DEF_obj_mac_s43__h16572;
      vcd_write_val(sim_hdl, num++, DEF_x__h11869, 5u);
      backing.DEF_x__h11869 = DEF_x__h11869;
    }
}

void MOD_mk_Test::vcd_prims(tVCDDumpType dt, MOD_mk_Test &backing)
{
  INST_count.dump_VCD(dt, backing.INST_count);
  INST_obj_mac_pp00.dump_VCD(dt, backing.INST_obj_mac_pp00);
  INST_obj_mac_pp00_s2.dump_VCD(dt, backing.INST_obj_mac_pp00_s2);
  INST_obj_mac_pp00_s3.dump_VCD(dt, backing.INST_obj_mac_pp00_s3);
  INST_obj_mac_pp00_s4.dump_VCD(dt, backing.INST_obj_mac_pp00_s4);
  INST_obj_mac_pp01.dump_VCD(dt, backing.INST_obj_mac_pp01);
  INST_obj_mac_pp01_s2.dump_VCD(dt, backing.INST_obj_mac_pp01_s2);
  INST_obj_mac_pp01_s3.dump_VCD(dt, backing.INST_obj_mac_pp01_s3);
  INST_obj_mac_pp07.dump_VCD(dt, backing.INST_obj_mac_pp07);
  INST_obj_mac_pp10.dump_VCD(dt, backing.INST_obj_mac_pp10);
  INST_obj_mac_pp10_s2.dump_VCD(dt, backing.INST_obj_mac_pp10_s2);
  INST_obj_mac_pp10_s3.dump_VCD(dt, backing.INST_obj_mac_pp10_s3);
  INST_obj_mac_pp16.dump_VCD(dt, backing.INST_obj_mac_pp16);
  INST_obj_mac_pp21.dump_VCD(dt, backing.INST_obj_mac_pp21);
  INST_obj_mac_pp30.dump_VCD(dt, backing.INST_obj_mac_pp30);
  INST_obj_mac_pp35.dump_VCD(dt, backing.INST_obj_mac_pp35);
  INST_obj_mac_pp35_s2.dump_VCD(dt, backing.INST_obj_mac_pp35_s2);
  INST_obj_mac_pp41.dump_VCD(dt, backing.INST_obj_mac_pp41);
  INST_obj_mac_pp50.dump_VCD(dt, backing.INST_obj_mac_pp50);
  INST_obj_mac_pp57.dump_VCD(dt, backing.INST_obj_mac_pp57);
  INST_obj_mac_pp57_s2.dump_VCD(dt, backing.INST_obj_mac_pp57_s2);
  INST_obj_mac_pp77.dump_VCD(dt, backing.INST_obj_mac_pp77);
  INST_obj_mac_pp77_s2.dump_VCD(dt, backing.INST_obj_mac_pp77_s2);
  INST_obj_mac_pp77_s3.dump_VCD(dt, backing.INST_obj_mac_pp77_s3);
  INST_obj_mac_s11.dump_VCD(dt, backing.INST_obj_mac_s11);
  INST_obj_mac_s11_s2.dump_VCD(dt, backing.INST_obj_mac_s11_s2);
  INST_obj_mac_s11_s3.dump_VCD(dt, backing.INST_obj_mac_s11_s3);
  INST_obj_mac_s12.dump_VCD(dt, backing.INST_obj_mac_s12);
  INST_obj_mac_s13.dump_VCD(dt, backing.INST_obj_mac_s13);
  INST_obj_mac_s14.dump_VCD(dt, backing.INST_obj_mac_s14);
  INST_obj_mac_s15.dump_VCD(dt, backing.INST_obj_mac_s15);
  INST_obj_mac_s15_s2.dump_VCD(dt, backing.INST_obj_mac_s15_s2);
  INST_obj_mac_s16.dump_VCD(dt, backing.INST_obj_mac_s16);
  INST_obj_mac_s16_s2.dump_VCD(dt, backing.INST_obj_mac_s16_s2);
  INST_obj_mac_s16_s3.dump_VCD(dt, backing.INST_obj_mac_s16_s3);
  INST_obj_mac_s21.dump_VCD(dt, backing.INST_obj_mac_s21);
  INST_obj_mac_s21_s3.dump_VCD(dt, backing.INST_obj_mac_s21_s3);
  INST_obj_mac_s22.dump_VCD(dt, backing.INST_obj_mac_s22);
  INST_obj_mac_s22_s3.dump_VCD(dt, backing.INST_obj_mac_s22_s3);
  INST_obj_mac_s23.dump_VCD(dt, backing.INST_obj_mac_s23);
  INST_obj_mac_s23_s3.dump_VCD(dt, backing.INST_obj_mac_s23_s3);
  INST_obj_mac_s31.dump_VCD(dt, backing.INST_obj_mac_s31);
  INST_obj_mac_s32.dump_VCD(dt, backing.INST_obj_mac_s32);
  INST_obj_mac_s33.dump_VCD(dt, backing.INST_obj_mac_s33);
  INST_obj_mac_s34.dump_VCD(dt, backing.INST_obj_mac_s34);
  INST_obj_mac_s35.dump_VCD(dt, backing.INST_obj_mac_s35);
  INST_obj_mac_s36.dump_VCD(dt, backing.INST_obj_mac_s36);
  INST_obj_mac_s41.dump_VCD(dt, backing.INST_obj_mac_s41);
  INST_obj_mac_s42.dump_VCD(dt, backing.INST_obj_mac_s42);
  INST_obj_mac_s43.dump_VCD(dt, backing.INST_obj_mac_s43);
  INST_obj_mac_s44.dump_VCD(dt, backing.INST_obj_mac_s44);
  INST_obj_mac_x.dump_VCD(dt, backing.INST_obj_mac_x);
  INST_obj_mac_y.dump_VCD(dt, backing.INST_obj_mac_y);
  INST_obj_mac_z.dump_VCD(dt, backing.INST_obj_mac_z);
  INST_rg_a.dump_VCD(dt, backing.INST_rg_a);
  INST_rg_b.dump_VCD(dt, backing.INST_rg_b);
  INST_rg_c.dump_VCD(dt, backing.INST_rg_c);
}
